### ISSUE TITLE
Consider swapping staged/unstaged views

### ISSUE THREAD

**Issue by ProjectInfinity** [JetpackDuba/Gitnuro#10]
I suggest swapping the order of staged/unstaged views for the sake of consistency among git clients. It's personally an annoyance to me, but not much more than that.

I will provide you with examples here.

Gitnuro
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/593870/172945256-1f859196-38e6-4cc0-9e16-774bd0b26887.png">

GitKraken
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/593870/172945228-1c8d8a5d-f041-4d03-bd3d-71e1b1c3481a.png">

Sublime Merge
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/593870/172945175-a7dd4c8a-e77e-4220-8624-de865d874a6e.png">

As you can see the common thing to do seem to be to put unstaged files at top followed by staged files or in the example of SourceTree not use a staged/unstaged list. It seems like more consistent behaviour to me :)

**Comment by JetpackDuba** [comment]
The order is based on how Git CLI shows the status. I may add the option to invert them in the future when I add more customization settings.

**Comment by JetpackDuba** [comment]
![imagen](https://github.com/JetpackDuba/Gitnuro/assets/16917468/2494eca0-c1a9-479e-9424-43a0c2cd25c3)
