### ISSUE TITLE
Follow XDGBaseDir Standart

### ISSUE THREAD

**Issue by suwermave** [JetpackDuba/Gitnuro#112]
**Describe the bug**
XDG Base Directory specification defines where these files should be looked for by defining one or more base directories relative to which files should be located.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**To Reproduce**
Install application through any source including flatpak, see .gitnuro, probably also .java and .skiko in user home.

**Expected behavior**
Directories in XDG standard set folders, fallback if variables not set.

**Desktop (please complete the following information):**

- OS: Fedora 38 Silverblue
- Version: Latest Flatpak

**Comment by suwermave** [comment]
.java and .skiko is 100% created by Gitnuro
![изображение](https://github.com/JetpackDuba/Gitnuro/assets/50447661/b8f99492-47d9-4089-9a6f-9f11a5e86341)
![изображение](https://github.com/JetpackDuba/Gitnuro/assets/50447661/d3c7131e-6a38-4fef-b345-f08d723f1d2a)

**Comment by JetpackDuba** [comment]
> I believe it is possible for a custom path to be made for Java preferences - that would solve .java

Correct, I wasn't aware. Thanks for pointing it out!

> I opened issue at skiko library github to support the spec though it is unlikely due to Linux(x86_64) being unsupported

Linux is supported in Kotlin/JVM version (What I currenly use). The unsupported version is for Kotlin/Native.

**Comment by technobirb** [comment]
Flatpak's `--persist` option can be used to redirect those dot folders. ([Or Flatseal as shown here.](https://github.com/flathub/cc.arduino.IDE2/blob/master/limit-filesystem-access.md)) Is it possible to define this in the Flathub manifest so users don't need to add it themselves?
