### ISSUE TITLE
Add Version number

### ISSUE THREAD

**Issue by luri-fr** [JetpackDuba/Gitnuro#114]
Hi,

Ty for you're hard work.

Is it possible to add version numerber of the software somewere in GUI ?
This will help for know if we have the last version or not.

Ty

**Comment by JetpackDuba** [comment]
Hey!

It's it is shown when you open a new tab.

![imagen](https://github.com/JetpackDuba/Gitnuro/assets/16917468/ca8ff55c-ada8-476e-9765-26c0cab39db9)


I plan to add a label at the bottom of every repo to notify if there is new version.
