### ISSUE TITLE
Remote Branch 'HEAD' not found in upstream origin

### ISSUE THREAD

**Issue by luri-fr** [JetpackDuba/Gitnuro#115]
**Describe the bug**
Hi,

Normally I've use GIT_SSH environnement variable to use Putty but this not work with Gitnuro. (I've soon open an other issue about this.)
For test, I copy my SSH private key on ~/.ssh/  and config an ~/.ssh/config file.
In Git Bash, an ssh://mygit work as excpected.

But Gitnuro clone not working. I have *Remote branch 'HEAD' not found  in upstream origin*

git clone on a Powershell command line working fine. (but git command line use Putty)

How can I do for clone work in Gitnuro ?
ty for you're help,
sincerly

**Expected behavior**
Clone working in GUI

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version 22H2
- Git server : gitolite3 v3.6.10-2-g64aa53b on git 2.30.0

**Comment by luri-fr** [comment]
Log with gitnuro launch of git bash : 
`$ ./gitnuro
After reading prefs, got 1 tabs
TabViewModel - Trying to open repository C:\datas\documents\projets\test
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
TabViewModel - Refreshing repository state SAFE
Failed to choose DirectX12 adapter.
SystemUtils - OS is windows 10
SystemUtils - OS is windows 10
git-upload-pack '/o2.git'
Authentication completed with success
SystemUtils - OS is windows 10
git-upload-pack '/ansible.git'
Authentication completed with success`

**Comment by JetpackDuba** [comment]
Putty is not supported by LibSSH https://gitlab.com/libssh/libssh-mirror/-/issues/45

About the issue itself... If I'm very honest, I've got no clue. I'll try to setup a gitolite3 to see if it does something unexpected. I'll get back to you in a bit.

**Comment by JetpackDuba** [comment]
> Log with gitnuro launch of git bash :
> 
> ...

Can you check the logs in `USER_DIR/.gitnuro`?  I was expecting more info about it than just that o_O

**Comment by luri-fr** [comment]
Hi,
Ty for you're help and work.

I'm not found the .gitnuro file. How can i activate log ?

```
About the issue itself... If I'm very honest, I've got no clue. I'll try to setup a gitolite3 to see if it does something unexpected. I'll get back to you in a bit.
```
Ty but don't make that just for me. Save you time for other thinks.

```
Putty is not supported by LibSSH https://gitlab.com/libssh/libssh-mirror/-/issues/45
```
Bad news for me.
gitnuro not have the same behavior than git command line. I'm assume you can't simly use the git command line. 
never mind ;-)

**Comment by JetpackDuba** [comment]
It's weird because I've tried it and the repository created by gitolite uses the master branch o.O

In any case, it's something of JGit internals, I don't think it's worth the effort if it can be solved easily.

Thanks for sharing your solution!
