### ISSUE TITLE
Scrollbar covers information in sidepanel

### ISSUE THREAD

**Issue by ProjectInfinity** [JetpackDuba/Gitnuro#12]
On main branch, if you have a lot of local or remote branches, a scrollbar will appear and cover information and buttons in the sidepanel.

I have confirmed this on Linux without screen scaling.

![image](https://user-images.githubusercontent.com/593870/175932521-90e4ebfd-ce52-45dc-9439-bb7c656ded90.png)

**Comment by JetpackDuba** [comment]
Yes, I'm aware. I'll probably push the changes later today.
