### ISSUE TITLE
After installing Git 2.41.0 64-bit and rebooting, authentication is not working anymore on push & pull

### ISSUE THREAD

**Issue by Flashdown** [JetpackDuba/Gitnuro#126]
**Describe the bug**
I was using Gitnuro for quite some time now, then I decided to install Git and took the latest 2.41.0 64 bit installer for Windows. Everything was working fine until I've rebooted.  Now I can not push and pull anything anymore. It says authentication not supported.

When I close Gitnuro and delete the repo folder, then I can start Gitnuro again and clone the Gitea repo again, but it takes an unusual long time to start doing something: It just shows starting... for some time after entering url and folder. Then a user password dialog is presented, filled out and it starts cloning. From now on, when I try to push or pull again, it always fails instantly with authentication not supported. 

**To Reproduce**

1. Install Gitnuro
2. Install Git 64 Bit: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/Git-2.41.0-64-bit.exe
3. Keep recommended settings during install
4. Reboot
5. Try to push or pull in an existing repo. It fails.
6. Close Gitnuro and then uninstall Git
7. Open Gitnuro and it works correctly again

**Comment by JetpackDuba** [comment]
It's installed by default on Git for windows. You could try installing an older version of Git to check if it makes any difference.

I don't really know what could be wrong. Is it possible to test if it works with SSH?

**Comment by JetpackDuba** [comment]
Could you please test with the latest version of Gitnuro to see if that still happens?

**Comment by JetpackDuba** [comment]
I'm closing it as there hasn't been any additional feedback. Let me know if the issue still persists.
