### ISSUE TITLE
"Stage all" can be very slow

### ISSUE THREAD

**Issue by miroirdelame** [JetpackDuba/Gitnuro#129]
For some reason (that I don't know), using the "Stage all" feature usually takes a long while (~ 10 seconds), even though there is actually 1 file to stage. Staging one single file is, on the contrary, instantaneous. 

So couldn't it be relevant that the "Stage all" button just stages all files in the list file by file (I guess it currently proceeds differently, maybe using a dedicated git command) ? I have no idea of the possible drawbacks, so please take that as a simple suggestion :)

**Comment by JetpackDuba** [comment]
Hey! Just quick update: With yesterday's commit, I've been able to reduce the staging time to even less than 10% of what took before in big repositories.
