### ISSUE TITLE
Highlight changes within a line in diff

### ISSUE THREAD

**Issue by Compizfox** [JetpackDuba/Gitnuro#131]
**Is your feature request related to a problem? Please describe.**
When only small changes within a line occur, it is hard to spot them in a normal diff.

**Describe the solution you'd like**
Add support for diffing changed characters within a line, like `git diff --color-words`.

What would be even better is to keep the change on separate lines, but highlight the changed characters within the line.

See [this](https://stackoverflow.com/questions/29766752/git-diff-with-combined-word-diff) thread for an overview of the different methods.

**Comment by JetpackDuba** [comment]
Thanks for your suggestion!

Given that JGit does not provide such utility, seems like  a line by line comparison would be ideal. Google has a library which may be useful https://github.com/google/diff-match-patch

I'll look into it in the future (probably for v1.5) as I'm interested in the feature myself.

**Comment by julius-boettger** [comment]
This would be a big quality of life improvement for me. I like the way Github does it, highlighting the changed part of a line with a stronger color, e.g.

<img src="https://github.com/JetpackDuba/Gitnuro/assets/85450899/e301162f-3850-4d73-83c7-77d3513bb316" width="400">

Meanwhile in Gitnuro, the difference is pretty hard to spot.

<img src="https://github.com/JetpackDuba/Gitnuro/assets/85450899/9819dc73-294a-4411-b6a2-27d3f46bf44b" width="300">

**Comment by JetpackDuba** [comment]
Adressing this issue will be part of v1.5.0 as it's work in progress.

**Comment by julius-boettger** [comment]
That's great news! I'm excited to try it out when it's ready.

**Comment by JetpackDuba** [comment]
Screenshot of how it's looking 
![imagen](https://github.com/user-attachments/assets/17bbefd7-d1f4-42e4-b454-64ab1dc0d11d)

Colors will be probably tweaked after doing some contrast checks.
