### ISSUE TITLE
SSH regression from 1.2.1 to 1.2.0

### ISSUE THREAD

**Issue by suwermave** [JetpackDuba/Gitnuro#132]
**Describe the bug**
When trying to clone repo or create branch Gitnuro asks for password. It happens to be a password for SSH key (passphrase). In 1.2.1 I was trying to insert both passphrase and Gitlab password, and not only Gitlab but it failed loading forever. After installing 1.2.0 and inserting passphrase it worked smoothly. 

I am extremely sorry, not much time right now to format the issue correctly

**Desktop**

- OS: Fedora Workstation
- Version 38
Flatpak

**Comment by JetpackDuba** [comment]
Hey, thanks for your report!

That's... Unexpected, as the only change from Gitnuro's part was related to enabling additional SSH format. Perhaps the upgrade to libssh 0.10.5 (from 0.10.4) broke something.

Can you please get the logs from `$HOME/.gitnuro` ? Running the app from the command line with `flatpak run com.jetpackduba.Gitnuro` will also output the logs.

**Comment by suwermave** [comment]
[gitnuro.log](https://github.com/JetpackDuba/Gitnuro/files/11884978/gitnuro.log)
Here you go

**Comment by suwermave** [comment]
No, don't think so

**Comment by JetpackDuba** [comment]
Sorry for the late response. Are you perhaps using a custom SSH configuration? This file to be more precise: `~/.ssh/config` (or a custom path).

**Comment by JetpackDuba** [comment]
Could you please test with the latest version of Gitnuro to check if that bug still reproduces?

**Comment by JetpackDuba** [comment]
I'm closing the issue for now, let me know if it still reproduces and we can reopen it.
