### ISSUE TITLE
Font is too small on Pop Os

### ISSUE THREAD

**Issue by aakash3771** [JetpackDuba/Gitnuro#14]
I am new user. As soon as I opened the app I couldn't see the text. There is no font setting either. I am struggling to use this app.

**Comment by JetpackDuba** [comment]
Hey! Are you using a screen with scaling? Can you share your screen specs?

Font settings will be added soon but unless using scaling (aside from sight issues) should be fine.

**Comment by noplanman** [comment]
Same issue for me.

Here the display settings:
![hidpi-settings](https://user-images.githubusercontent.com/9423417/182036009-5e9bd411-93e9-4bd1-9940-28d0e094dbe0.png)

Here the Gitnuro interface:
![gitnuro-tiny](https://user-images.githubusercontent.com/9423417/182036008-aa70a459-3b7b-4cd3-b597-b9b61cb45831.png)

**Comment by JetpackDuba** [comment]
Yeah, exactly what I was thinking about. It's related to this issue https://github.com/JetBrains/compose-jb/issues/188

I'll try the mentioned workarounds in the linked issue, otherwise we may have to wait for it to be fixed. I can add the settings to adjust the font size but it won't help with the other UI settings.

**Comment by noplanman** [comment]
I've seen in some apps a setting to define the UI scale.
Maybe something like that can be added?

(if I remember which app has this, I'll let you know)

**Comment by JetpackDuba** [comment]
I've just found a way to set it programmatically. I'll add an option in the settings which will be included in 1.0.0 (It will be released this week).

**Comment by JetpackDuba** [comment]
Here is a screenshot of the new setting:

![imagen](https://user-images.githubusercontent.com/16917468/182726346-85d49eee-ca89-434b-8d22-9ff9005dc66b.png)

I'll leave the issue open until it gets fixed on compose.

**Comment by noplanman** [comment]
Great @JetpackDuba! Looking forward to giving Gitnuro a go when this is in.

**Comment by aakash3771** [comment]
ok the increase in font from 100% to 150% is too big. Can we enter the % manually. Thanks

**Comment by JetpackDuba** [comment]
Not for now.

I'm uploading version 1.0.1 with a few hotfixes and with an additional scaling option of 125%.

It will be available in a few hours.

**Comment by JetpackDuba** [comment]
Did the option of 125% work for you @aakash3771 ? If so, I'll close the issue.
Also interested in your feedback @noplanman :smiley:

**Comment by noplanman** [comment]
Hi @JetpackDuba the UI scaling is perfect now, thanks!

And thanks for your kind nudge for me reply here :wink:

I'll play around more with Gitnuro and hope it finds a place in my workflow, cause it looks really nice and clean, well done!

**Comment by noplanman** [comment]
Hi @JetpackDuba the UI scaling is perfect now, thanks!

And thanks for your kind nudge for me reply here :wink:

I'll play around more with Gitnuro and hope it finds a place in my workflow, cause it looks really nice and clean, well done!

**Comment by JetpackDuba** [comment]
> Hi @JetpackDuba the UI scaling is perfect now, thanks!
> 
> And thanks for your kind nudge for me reply here wink
> 
> I'll play around more with Gitnuro and hope it finds a place in my workflow, cause it looks really nice and clean, well done!

Thanks to you :smile: Feel free to share if you have got any suggestions.

I'll close the issue meanwhile, if anything we can reopen it.

**Comment by RichardFevrier** [comment]
I wish to have more control on the fonts from the `JSON`theme file 🙂

**Comment by JetpackDuba** [comment]
What's the use case for it, @RichardFevrier ? Feel free to open a new issue to discuss it.
