### ISSUE TITLE
Force push should default to with lease by default

### ISSUE THREAD

**Issue by JasonEleventeen** [JetpackDuba/Gitnuro#147]
Force push should never be default, allow optional force push if lease fails

```git push --force-with-lease```

This will prevent accidental overwrite of history on the origin

**Comment by JetpackDuba** [comment]
Hey!

I remember @DPini recommended me to do it but JGit had some weird issues, it was quite some time ago so it may be different with the newer versions.

I'll try it again, thanks for the reminder!
