### ISSUE TITLE
crash on trying to push via ssh on a repository without the necessary rights.

### ISSUE THREAD

**Issue by adam-ce** [JetpackDuba/Gitnuro#148]
**Describe the bug**
gitnuro crashes if you try to push to a git repository via ssh, where you don't have the necessary rights

**To Reproduce**
1. Clone e.g. "git@github.com:graphdeco-inria/gaussian-splatting.git" (which i suppose is not writeable by you)
2. Click on push
3. wait and it'll crash

**Expected behavior**
Error message, that you can't push to that remote.

**Screenshots**
I've attached a [an error log file](https://github.com/JetpackDuba/Gitnuro/files/12064209/hs_err_pid3.log)

**Desktop (please complete the following information):**
- OS: Kubuntu 22.04
- Version: 1.2.1

**Comment by JetpackDuba** [comment]
Hey! Thanks for your report!

Apparently it was fixed as a side effect of the changes in 9a7cc6a988223cf9c2071996d8869d7bb981783f . I noticed that resources where not being closed in the right order but I didn't find a case where this would have been a problem, until now :smile: 

The fix will be available for v1.3.0.
