### ISSUE TITLE
Login failed every connect

### ISSUE THREAD

**Issue by eitsedna** [JetpackDuba/Gitnuro#15]
Login failed after clone
Login failed after push
Login failed after connect to git server

**Comment by JetpackDuba** [comment]
How do you authenticate with the server, using SSH or HTTP(S)? In case of SSH, what signature algorithm?

Can you start gitnuro from a CLI and paste any log related to an exception?

**Comment by JetpackDuba** [comment]
I will close the issue next week if there is no additional feedback.
