### ISSUE TITLE
Simple commit's SHA copy

### ISSUE THREAD

**Issue by BasilYes** [JetpackDuba/Gitnuro#150]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when need to get commit's SHA and can't do it as simple as in github

**Describe the solution you'd like**
Just one button in the RMB commit menu 

**Describe alternatives you've considered**
Alternatives copy it in github or use git log

**Additional context**
Github realisation:
![image](https://github.com/JetpackDuba/Gitnuro/assets/36816595/fd91bb7d-7f6a-4554-b686-b7bcc47b74b4)

What I want:
![image](https://github.com/JetpackDuba/Gitnuro/assets/36816595/eee2537b-3085-40ee-9c5c-1d12d1934b18)

**Comment by JetpackDuba** [comment]
Hey!

You can click on a commit and click on the SHA, it will be copied to the
clipboard.

**Comment by BasilYes** [comment]
Thanks, I just didn't notice this.
