### ISSUE TITLE
Fetch all should skip missing remotes

### ISSUE THREAD

**Issue by JasonEleventeen** [JetpackDuba/Gitnuro#153]
**Describe the bug**
Fetch all should skip missing remotes

**To Reproduce**
Delete a remote branch, fetch all

**Comment by JetpackDuba** [comment]
It should not, it should delete the remote branch reference locally. It's actually coded this way but there is a weird bug in JGit that produces an error instead of simply deleting the reference.

I've tried to debug it but without much success for now as I hadn't invested much time.

**Comment by JetpackDuba** [comment]
Ah there is already an [issue](https://github.com/JetpackDuba/Gitnuro/issues/123) about it. Closing this as it seems a duplicate, let me know if I've missunderstood  you.
