### ISSUE TITLE
Flatpak reference is broken

### ISSUE THREAD

**Issue by santiihoyos** [JetpackDuba/Gitnuro#154]
**Describe the bug**
Flatpak reference is broken

**To Reproduce**

1. try to install followin steps in readme.md
2. run: flatpak install --user com.jetpackduba.Gitnuro

**Expected behavior**
application is installed

**Screenshots**

Error: error: No remote refs found similar to ‘com.jetpackduba.Gitnuro’

**Desktop (please complete the following information):**

- OS: Ubuntu
- Version 22.04

**Comment by ProjectInfinity** [comment]
It sounds like you could be missing the flathub remote.

What shows in your terminal when you type `flatpak remotes`?

I just attempted to reinstall Gitnuro from flathub and it is successful.
```
flatpak install Gitnuro
Looking for matches…
Found ref ‘app/com.jetpackduba.Gitnuro/x86_64/stable’ in remote ‘flathub’ (system).
```

**Comment by JetpackDuba** [comment]
> It sounds like you could be missing the flathub remote.
> 

Agreed


`flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

I'll update the readme to mention it as well as explain the optional user flag.
