### ISSUE TITLE
Custom Scale Amount

### ISSUE THREAD

**Issue by yougotwill** [JetpackDuba/Gitnuro#156]
Firstly thank you for this amazing app! It's really well polished.

I've been tweaking the UI Scale to get it just right for me and settled on 175% probably being right. That is a bit niche to request as an option so it would be great if we had the option to set a custom scale amount please 🙏

**Comment by JetpackDuba** [comment]
Thanks for your kind words :smile: 

I'll try to look into it for v1.4. Meanwhile, I can add a few more options for v1.3 release (will be released soon) so you don't have to wait until this feature is implemented.

**Comment by JetpackDuba** [comment]
Release 1.3 is out with the new 175% option 😁

**Comment by yougotwill** [comment]
Thank you @JetpackDuba!

**Comment by JetpackDuba** [comment]
Instead of allowing a custom value (which can be a bit problematic due to value handling), I've added a bunch of new values such as 75%, 225% and 275%. If anyone needs more I can add them but seems unlikely.

**Comment by artur-ag** [comment]
Would it be possible to add 90% and 80%, like in GitKraken? 75% is quite a big jump from 100%, at least for me. Thanks for considering this!
