### ISSUE TITLE
Support for Git Credential Manager

### ISSUE THREAD

**Issue by alensiljak** [JetpackDuba/Gitnuro#16]
Hi! Just found out about Gitnuro and am pretty impressed by how convenient it is to work with. Thanks for that!

I have a repository in Azure DevOps and the Git CLI is configured to use Git Credential Manager ( `git config --global credential.helper manager-core` ). This allows the CLI to pull and push from DevOps-hosted repository using MFA. This also applies for MFA-secured GitHub repositories.

However, when pulling through Gitnuro, the authentication window pops up every time. Is there a way to recognize and use the stored credentials?

**Comment by JetpackDuba** [comment]
Hey! Thanks for your words :)

I must admit that I've never worked with Git Credential Manager but digging a bit into de documentation of JGit, there is no built-in implementation to support such authentication method. In other words, I'll have to add it myself (I'll try to do it for 1.1.0 which should be released sometime in october).

The alternative for now would be using SSH or use the CLI for remote operations with authentication.

**Comment by JetpackDuba** [comment]
I have added support for external credentials helper in general for release 1.1.0. It needs more testing but it should work. The only caveat is that Gitnuro requires to have the full path of the external helper executable. Example in Linux: `helper = /usr/share/git-credential-manager-core/git-credential-manager-core`

`store` and `cache` values to the helper are not supported for now.

**Comment by JetpackDuba** [comment]
Gitnuro 1.1 was released this last weekend, please give it a try and let me know if works as expected :smile:

**Comment by JetpackDuba** [comment]
Forgot to show an example for windows!

Here it goes how I've configured my .gitconfig:

```
[credential]
	helper = C:/Program Files/Git/mingw64/bin/git-credential-manager-core.exe
```

I'll also add it to the README.

**Comment by alensiljak** [comment]
Thanks for the reminder. Due to similar issues with other applications, I've switched all my repos to be accessed via SSH. That is now causing a different issue where existing git setup and keys are not recognised. :(
