### ISSUE TITLE
Mac: “Gitnuro.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by ADTC** [JetpackDuba/Gitnuro#160]
When installing first time on Mac from Zip or via `brew`, I get warned when trying to run the `.app`:
> “Gitnuro.app” cannot be opened because the developer cannot be verified.
> macOS cannot verify that this app is free from malware.

<img width="260" alt="image" src="https://github.com/JetpackDuba/Gitnuro/assets/6047296/4589aa6c-60c9-4af7-9e66-77f05636d80f">

**Expected behavior**
The app is signed by Apple, so that the developer can be verified. (There are ways to automate this via Apple's servers. I've done it before.)

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.5 (22G74)
- Version 1.2.1

**Comment by ADTC** [comment]
Currently we can still bypass this (accepting all risks), by context-clicking (right-clicking) the app in Applications and clicking Open, then Open again in the presented dialog:

<img width="260" alt="image" src="https://github.com/JetpackDuba/Gitnuro/assets/6047296/63f30b36-b0a6-4d2a-9cd2-1d5511168874">

This is far from ideal from a security standpoint though.

**Comment by JetpackDuba** [comment]
Hey,

Yeah, it's stated in the README. I may do it in the future but not any time
soon as I don't own a mac and the pricing for the dev cert is quite
expensive for a FOSS project without profit.

**Comment by ADTC** [comment]
Yeah, it's quite sad that the [Fee Waiver](https://developer.apple.com/support/membership-fee-waiver/) option is not available to "Individuals and sole proprietors/single-person businesses.". Anyway thanks for letting me know.
