### ISSUE TITLE
Clicking "Split Diff" can never be changed back because the button just disappears

### ISSUE THREAD

**Issue by moqmar** [JetpackDuba/Gitnuro#169]
**Describe the bug**
Buttons in the top bar disappear when clicking "Split diff".

**To Reproduce**

1. Change a file
2. Click it
3. Click the "Split diff" icon
4. Try to somehow get back to the "Unified diff"

**Expected behavior**
I can click on "Unified diff" again to go back to the previous view

**Screenshots**

Before the click: 
![grafik](https://github.com/JetpackDuba/Gitnuro/assets/5559994/77f560cd-1353-406d-8abc-edb6950ba3ef)

After the click:
![grafik](https://github.com/JetpackDuba/Gitnuro/assets/5559994/8cdcd165-52bf-4149-9fe6-3643180c5154)

**Desktop (please complete the following information):**

- OS: Linux
- Version 1.3.0

**Workaround:**
```
sed -i '/diffType/d' ~/.var/app/com.jetpackduba.Gitnuro/config/gitnuro/.java/.userPrefs/GitnuroConfig/prefs.xml
```

**Comment by JetpackDuba** [comment]
Hey!

Sorry for the late response, I was on vacation.

I thought I fixed this issue before the release but apparently not, my bad. I'll fix in the v1.3.1 that will be released this weekend.
