### ISSUE TITLE
v1.3.0 blocked by Symantec Endpoint protection

### ISSUE THREAD

**Issue by AbraxasDMG** [JetpackDuba/Gitnuro#172]
Hi.

Just wanted to let everyone know that SEP blocked portable windows version. Reported risks are AGR.Terminate!g2 and SONAR.Dropper for gitnuro.exe and gitnuro.log (?) files.

**Comment by JetpackDuba** [comment]
Probably due to usage of Rust, I've seen some false positives in the past. I'd recommend whitelising Gitnuro. If you don't trust it, you can always build it yourself and trust it.

**Comment by JetpackDuba** [comment]
I've used [virustotal to check the latest releases](https://www.virustotal.com/gui/file/6a94e092c9daef4ebc8444441b7c6e0e47455766822c377d79041605d8657282/detection) of Gitnuro and everything looks great, not a single problem detected, if the issue keeps popping up I'll try to email Symantec.
