### ISSUE TITLE
Forgejo Accounts Connection

### ISSUE THREAD

**Issue by rrangelo** [JetpackDuba/Gitnuro#173]
Would be great can connect with [Forgejo](https://forgejo.org/) account like GitHub Desktop does with GitHub Accounts or SourceTree with BitBucket. It can be do it like [GitNex](https://gitnex.com/) did it. [GitNex](https://gitnex.com/) is a FOSS made for [Forgejo](https://forgejo.org/) from Android.

Source Core: https://codeberg.org/gitnex/GitNex

Public cloud servers for [Forguejo](https://forgejo.org/) are:

- [Codeberg](https://codeberg.org/)
- [Disroot Git](https://git.disroot.org/)

I use [Disroot](https://disroot.org) and I would thank you so much for it.

**Comment by JetpackDuba** [comment]
Hey! Thanks for your suggestion.

What would be the use case? Or what advantages would it have to add such feature?

**Comment by rrangelo** [comment]
Like GitHub Desktop or SourceTree with their providers. It helps us with: 

- Remote repositories easy access.
- Manage account, organizations, repositories, notifications and many more.
- Explore repositories, organizations, issues and users
- Safe connection
- Encrypt end-to-end

Attached below a screen of GitNex app:

![GitNex](https://github.com/JetpackDuba/Gitnuro/assets/68767628/ef07b444-c4f3-4b70-8536-6b1b6925e2d9)

**Comment by JetpackDuba** [comment]
Why don't you just use the WebUI of the platform? Gitnuro is a generic Git client, not for a specific platform or a replacement for the existing Web UIs. There are plans to add some integration with the most popular backends (nothing clearly defined tho) but nothing like this.

**Comment by JetpackDuba** [comment]
As there aren't enough reasons to add such feature, I'm closing this issue. Let me know if you would like to discuss anything else.
