### ISSUE TITLE
"Change upstream branch" Crash

### ISSUE THREAD

**Issue by DaegorDude** [JetpackDuba/Gitnuro#174]
**Describe the bug**
When right-clicking my one and only local branch, selecting "Change default upstream branch", and clicking either drop-down for remote or branch, an error pops up and Gitnuro crashes.

**To Reproduce**

1. Open a repo with a single local branch.
2. Right-click this branch and select "Change default upstream branch".
3. Click on either drop-down under "Remote" or "Branch".
4. Receive crash dialogue.

**Expected behavior**
Probably nothing considering I have no other remotes or branches.

**Screenshots**
https://imgur.com/oy3umTN

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 1.3.0

**Comment by JetpackDuba** [comment]
Thanks! Fixed!
