### ISSUE TITLE
Remember layout changes made by the user across sessions

### ISSUE THREAD

**Issue by esotericist** [JetpackDuba/Gitnuro#176]
**Is your feature request related to a problem? Please describe.**
the column widths of the view as shipped are typically not matching what i need for visibility, either by taking up too much or not enough horizontal space.

**Describe the solution you'd like**
it'd be nice if the sizes i select persist across sessions, so i don't have to keep adjusting them. bonus points if they're remembered on a per-project basis.

**Describe alternatives you've considered**
i'm not sure what alternatives exist other than 'be irritated' or 'use something else'

**Additional context**

what i set the leftmost pane to look like:
![image](https://github.com/JetpackDuba/Gitnuro/assets/1569754/688e6c75-87d4-46e4-a7b3-d9bb9498dee5)

what that pane looks like next time i reopen the client:
![image](https://github.com/JetpackDuba/Gitnuro/assets/1569754/87089f75-158c-4a30-87e2-014618f8f58b)

also applies to the rightmost pane.

**Comment by JetpackDuba** [comment]
Hey! Thanks for the detailed report.

I've been considering implementing it but I've faced a few issues, some technical (how resizing behaves in the splitpane it's a bit problematic) and some from the UX perspective.  I'll add it to 1.5.0 since I'd like to do smaller releases (but to be released sooner instead of every 6 months).

**Comment by esotericist** [comment]
no rush, it happens when it happens. i'll regularly try to live in it, and give you more complaints when i find stuff i can't stand :)

for now i'm back in gitkraken to get work done, but i very much want to see this progress so i will try to be a constructive participant as time and energy allows.
