### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Plat01** [JetpackDuba/Gitnuro#181]
I can't install Gitnuro v1.3.1 the way you describe in "Release page" (via flatpak `flatpak install --user com.jetpackduba.Gitnuro`)

```
  ~$ flatpak install --user com.jetpackduba.Gitnuro
  Looking for matches…
  error: No remote refs found similar to ‘com.jetpackduba.Gitnuro’
```

- OS: Linux
- Version: Ubuntu 22.04

**Comment by JetpackDuba** [comment]
Hey! 
You probably haven't set up the flathub repository. Check this https://github.com/JetpackDuba/Gitnuro#downloadinstall
`flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

**Comment by JetpackDuba** [comment]
Closing the issue as there isn't much more to discuss :)
