### ISSUE TITLE
git fetch problem

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [JetpackDuba/Gitnuro#183]
**Describe the bug**
When i found remote has some updates, i try to use the button to fetch my repository, then Gitnuro raise an error to me, everytime i open Gitnuro it will change a number. But i can fetch successfully by git bash.

**To Reproduce**

1. Open Gitnuro
2. Click on fetch button
3. Wait until it raise error

**Expected behavior**
fetch from remote successfully

**Screenshots**
![image](https://github.com/JetpackDuba/Gitnuro/assets/61617417/965a206a-29cb-463c-871d-fd36318d58d0)

**Desktop (please complete the following information):**

- OS: Windows 11 23h2(beta)
- Version 1.3.1

**Comment by lingfengyu-dreaming** [comment]
and gitnuro will use a pack when running, if i use `git fetch --refetch`, i will see a error saying "unlink of pack-? failed", i should close gitnuro to unlink it successfully.

**Comment by JetpackDuba** [comment]
Hey!

It's a known bug in JGit, see #123
