### ISSUE TITLE
Does Gitnuro currently support git-LFS? 

### ISSUE THREAD

**Issue by narFnarF** [JetpackDuba/Gitnuro#185]
Hi!
Quick question:
Does Gitnuro currently support git-LFS? (If no, is there plan to support it?)

**Comment by JetpackDuba** [comment]
Hey!

Kind of, it should work when there aren't any authentication restrictions but that not usually the case so it would fail.  In other words, authentication has yet to be implemented if I'm not mistaken.

**Comment by VortexAcherontic** [comment]
I'd just like to shim in and note that the flatpak does miss the git-lfs binary as no lfs repo seems to work for me using the flat

![grafik](https://github.com/JetpackDuba/Gitnuro/assets/11244092/7dbe1fc9-4582-4b13-b7d4-3457502956b4)

**Comment by JetpackDuba** [comment]
I'll close this issue, further discussion can be done here https://github.com/JetpackDuba/Gitnuro/issues/215
