### ISSUE TITLE
Can "Rebase interactive" use origin date?

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [JetpackDuba/Gitnuro#187]
**Is your feature request related to a problem? Please describe.**
When use "Rebase interactive", it will make all those changed commits come into the newest place in commit tree, and make those eariler commit be later than later commit.

**Describe the solution you'd like**
Add a checkbox to select "use origin commit date" and let jgit rebase with origin date.

**Describe alternatives you've considered**
Maybe sourcetree or other tools.

**Additional context**
![image](https://github.com/JetpackDuba/Gitnuro/assets/61617417/1c24c94e-9bf6-4717-a054-7d96d5ddfed8)

**Comment by JetpackDuba** [comment]
Sorry but I'm not sure what do you mean. Do you want to be able to see the committer date instead of the author date? When using the author date and rebasing, you may have older commits ahead of newer ones.
