### ISSUE TITLE
Resources sites (git-scm.com/flathub.org) have the wrong project link/URL.  Getting site not found error in browser.

### ISSUE THREAD

**Issue by jammiben** [JetpackDuba/Gitnuro#188]
Resources sites have the wrong project link/URL.  Getting site not found error in browser.

This may deter some users from using your app.

https://git-scm.com/downloads/guis/
https://flathub.org/apps/com.jetpackduba.Gitnuro

I believe the link needs to be changed from https://gitnuro.jetpackduba.com/ to https://gitnuro.com/

**Comment by JetpackDuba** [comment]
Hey!

Yeah, I wanted to update the website and the URL but ended up doing nothing due personal issues. Thanks for the reminder, I'll try to update it in a few hours.
