### ISSUE TITLE
Connects to 185.199.111.133 

### ISSUE THREAD

**Issue by gerroon** [JetpackDuba/Gitnuro#193]
Hi

I know it is mentioned that this does not track any data but I want to make sure what this initial IP connection is. Can you please clarify if this app does any form of phoning, update checks etc?  I do not see a way to disable updates in the preferences.

thanks

**Comment by JetpackDuba** [comment]
Hey!

It's the updates check pointing to this URL https://github.com/JetpackDuba/Gitnuro/blob/main/src/main/kotlin/com/jetpackduba/gitnuro/AppConstants.kt#L27

As for now, there isn't any way of disabling the check.
