### ISSUE TITLE
Remote authentication is not supported!!!

### ISSUE THREAD

**Issue by GorIvanov** [JetpackDuba/Gitnuro#196]
This app can't be used because authentication is not supported for remote repositories...
Please fix this, because without that this app doesn't make any sense. 
It's useless.

**Comment by JetpackDuba** [comment]
Without more information there isn't much I can do. What is failing? HTTP or SSH? Gitnuro supports both

**Comment by GorIvanov** [comment]
Can't push via HTTP
![image](https://github.com/JetpackDuba/Gitnuro/assets/39217038/755d4cf5-616f-41fd-bb8c-a5f97594e542)

**Comment by JetpackDuba** [comment]
There seems to be something weird going on. A few questions: 
Are you using some kind of credentials manager? 
What OS are you using?
Is it a public repository (or a public service such as Github/Gitlab/etc)?
-- 
Can you share the logs?
Windows `%LOCALAPPDATA%\Gitnuro\logs`
Linux `~/.local/state/gitnuro/logs` (Unless you have defined XDG_STATE_HOME with a different path).
Mac `UserHome/Library/Logs/com.jetpackduba.Gitnuro/`

The logs may have references to the remote URL, please remove them if that is sensible data.

**Comment by GorIvanov** [comment]
This is a private repository (self-hosted) based on Gitea.
I use Windows 11.
When I use other apps like Sourcetree, Gitkraken, Gitahead...there is authentication request (automatically asked me to insert username and password). For example, this form Gittyup:
![image](https://github.com/JetpackDuba/Gitnuro/assets/39217038/e3371763-6fcd-44ef-98f2-801670a5488b)

Here are logs:
![image](https://github.com/JetpackDuba/Gitnuro/assets/39217038/7dfe340a-129d-49e5-97f9-47f2cc3de3f4)

**Comment by JetpackDuba** [comment]
You are using Git Credentials Manager, please check the last section of the
FAQ https://github.com/JetpackDuba/Gitnuro/#faq

**Comment by GorIvanov** [comment]
Thank you! It works. Not the easiest way but ok.

**Comment by JetpackDuba** [comment]
The error should be improved. I'll add it to #30
