### ISSUE TITLE
Preview support for GIFs

### ISSUE THREAD

**Issue by Nohus** [JetpackDuba/Gitnuro#2]

**Comment by aeab13** [comment]
It depends on this https://github.com/JetBrains/compose-jb/issues/153

I can try the sample provided there but it's not something that has the highest priority for now, so I'll wait at least until Gitnuro reaches beta. If  there isn't a builtin way in compose components, I'll add it myself.

**Comment by JetpackDuba** [comment]
I have implemented the GIF & WebP support in Compose [here](https://github.com/JetBrains/compose-jb/pull/2015). I will update gitnuro once Compose-jb 1.2.0 is released.
