### ISSUE TITLE
Change order of right sidebar

### ISSUE THREAD

**Issue by MarcusElgKTH** [JetpackDuba/Gitnuro#201]
**Is your feature request related to a problem? Please describe.**
It feels unintuitive to move your cursor downwards when your files move upwards. It just feels like an unnatural flow.

**Describe the solution you'd like**
Move the commit message settings to the top so it's next to the staged files. Makes much more sense imo, so the files move from unstaged to staged to pushed. Could also be a setting if some people prefer the old way
![image](https://github.com/JetpackDuba/Gitnuro/assets/90641975/10b8d709-be2d-4508-b382-942627fe5947)

**Comment by MarcusElgKTH** [comment]
> You can invert the staged/unstaged views if you prefer (unstaged at the top and staged at the bottom), but there are no plans to change the layout as you mention. Most users expect to decide what changes are committed and then write the message, as it's done in Git CLI.'

Ok, thanks for your answer. How can I invert the views?

**Comment by JetpackDuba** [comment]
Settings -> Layout -> Swap position for staged/unstagged views

Set it to true and the views will be swapped
