### ISSUE TITLE
Can't connect gitnuro to github.

### ISSUE THREAD

**Issue by dnkmmr69420** [JetpackDuba/Gitnuro#204]
Can't connect to github

**To Reproduce**

1. Clone repo
2. Make commits
3. Push commits
4. Enter github username and password
5. It's incorrect

![image](https://github.com/JetpackDuba/Gitnuro/assets/104856296/5c1332bc-8e9d-40d2-89ec-eb63244c39b1)

**Expected behavior**
Authenticates then pushes commits

**Screenshots**

**Desktop (please complete the following information):**

- OS: Linux
- Version: Flatpak

**Comment by dnkmmr69420** [comment]
I've figured it out

first install gh, then log in with gh, then go to ~/.config/gh/hosts.yml, then copy username to username then copy oauth token to password

**Comment by JetpackDuba** [comment]
You can't use your password to authenticate, it's something that GitHub changed a few years ago.  You need to generate an authentication token as explained here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

As mentioned in the other issue, you can also use Git Credentials Manager.
