### ISSUE TITLE
Discard specific line in diff

### ISSUE THREAD

**Issue by RichardFevrier** [JetpackDuba/Gitnuro#21]
Thank you for your work 🎉

Right click on content currently open the `copy` tooltip.
I wish to have the possibility to (un)stage/discard lines with a right click on a selected content 🙂

**Comment by JetpackDuba** [comment]
Thanks for your words :smile_cat: 

Stage/Unstage lines is already implemented for Gitnuro 1.1.0. I completly forgot about discard tho, I may add it before the release if I've got enough time, otherwise I'll add it for 1.2.0.

**Comment by Fabien-B** [comment]
That should be nice to have this feature indeed!
What would be nice is if we could select multiple lines (by just dragging over the lines) and either stage them or discard them. 
Thank you, this is an amazing work !

**Comment by JetpackDuba** [comment]
> That should be nice to have this feature indeed! What would be nice is if we could select multiple lines (by just dragging over the lines) and either stage them or discard them. Thank you, this is an amazing work !

Hey! Sorry for the late answer and thanks for your words :smiley: 

For now I've implemented the option to discard lines individually by using the context menu of each line. Discarding line in "bulk" would be a quiet complex thing to do with little gain (Or at least I think so, I may be wrong). I'd simply stage the lines that I want to keep (each line can be staged with a single click) and then discard the rest of the hunk.
