### ISSUE TITLE
Ability to limit number of loaded commits in commit history

### ISSUE THREAD

**Issue by algts** [JetpackDuba/Gitnuro#212]
**Is your feature request related to a problem? Please describe.**
It takes a lot of time to load commit history for big repositories like linux kernel and it may even fail to load it after several minutes (flatpak version).

**Describe the solution you'd like**
An option that allows limiting the number of loaded commits in commit history (for example, 100). This option should probably not be enabled by default.

**Comment by JetpackDuba** [comment]
Hello!

There is already such option and it's enabled by default with 1000 commits.

![imagen](https://github.com/JetpackDuba/Gitnuro/assets/16917468/a608f89d-2845-4a9c-83fd-752da06e7673)

**Comment by algts** [comment]
Ok, thanks a lot.
