### ISSUE TITLE
Using "stage hunk" often causes graphical issues in the diff panel

### ISSUE THREAD

**Issue by narFnarF** [JetpackDuba/Gitnuro#213]
**Describe the bug**
Using the "stage hunk" feature often causes the center panel (normally showing the diff) to have graphical issues. This makes the diff impossible to see for that file until unstaging the file.

**To Reproduce**

1. In your repo, edit a long file so that Gitnuro displays 2 hunks
2. Click on 'Stage hunk'
4. Look at the center (diff) panel. It displays a large square with "01" written on it, as well as the words "Old" and "New".

**Expected behavior**
The center panel displays the diff

**Screenshots**
![image](https://github.com/JetpackDuba/Gitnuro/assets/3538115/eeac97ac-48ef-4880-91d8-98432b28b473)

**Desktop (please complete the following information):**

- OS: Linux Mint
- Gitnuro version 1.3.1

**Comment by JetpackDuba** [comment]
Hey!

That's odd, what encoding are you using in your file? I've done some fixes regarding that recently, it could be the same issue.

**Comment by narFnarF** [comment]
I'm always using utf-8 for encoding.

Note that this is a new issue, that appeared, I would say, in the past 1-3 months. It used to work properly before.

**Comment by JetpackDuba** [comment]
Does this happen in multiple repositories/files or specific cases? Seems quite a strange behavior.

Gitnuro 1.4 will be released next week if you want to give it a try in case some of my changes to encoding has fixed also this issue.
