### ISSUE TITLE
[Proposal] New Icon

### ISSUE THREAD

**Issue by priahoud** [JetpackDuba/Gitnuro#219]
Hey!

I thought the Icon could use a little more Detail and Variation, so I sat down and played around a bit with the original Theme and while I was at it I cranked out some dark Variants too. I really like some of those asymmetric ones and am currently using one of the dark ones on my Machine.

Maybe this is something you are interested in or maybe you got some Ideas yourself?
Feel free to let me know what you think!

<img width="960" alt="Preview" src="https://github.com/user-attachments/assets/5809bd56-59ee-4db1-88f1-18519279ac51">

**Comment by JetpackDuba** [comment]
While I like the idea of improving the contrast between colors, I'm not a big fan of the 3D effect added to the "commit" nor the borders to the lines.

I've got a couple of variations of the icon, some with higher contrast and other using gradients to provide some depth to the icon but nothing feels "good enough".

Here is an example:
<img width="512" alt="Base" src="https://github.com/user-attachments/assets/3cb8c9aa-d102-4f20-b4e7-e4f1ad6b2895">


I didn't consider the option of having a dark themed icon, it's interesting! Not sure how feaseable it's technically, since it could hurt visibility depending on the user's task bar (it's kinda similar to Windows Dark task bar and other linux themes).

It's ultra low priority for now but perhaps in the future once I've launched the new website and revamped a bit the UI side (focused on UX right now).

I appreciate the effort tho :smiley_cat:

**Comment by priahoud** [comment]
> While I like the idea of improving the contrast between colors, I'm not a big fan of the 3D effect added to the "commit" nor the borders to the lines.

Yeah, those were just a quick experiment. Not sure I like them either. Here's the same icons without shading:

<img width="960" alt="Preview" src="https://github.com/user-attachments/assets/ff863bf8-d5f4-422e-a930-773fda8b0cfa">

... and a Screenshot of my Desktop using the 5d dark variant. I like it!

![screenshot](https://github.com/user-attachments/assets/79f4f8d5-f954-4fc3-acb7-dfd57ea564b4)

> I've got a couple of variations of the icon, some with higher contrast and other using gradients to provide some depth to the icon but nothing feels "good enough".

The main thing that was bugging me is that although the idea for the original design is a node-graph, the design itself is a little ambiguous. That is what motivated me to explore some alternatives - especially something non-symmetric because that is what most commit trees look like.
To me, the lower rows in the sheet with the 4x and 5x variants not only are immediately recognizable as node graphs, but they are generally more interesting to look at because they don't have symmetry. Your mileage may vary, of course.
And come on ... those dark variants just look delicious! 😀

> I didn't consider the option of having a dark themed icon, it's interesting! Not sure how feaseable it's technically, since it could hurt visibility depending on the user's task bar (it's kinda similar to Windows Dark task bar and other linux themes).

Yeah, that's why I placed all of them on different backgrounds to see how they would look on both desktop theme variants at a glance. I could also try to find some nice midtone variation for the background but honestly, there probably is no "safe" variant that works on all machines. If you got some suggestions I am all ears.
 
> It's ultra low priority for now but perhaps in the future once I've launched the new website and revamped a bit the UI side (focused on UX right now).

Understood. I can easily replace the icon on my machine anyway, which was my main objective here. I just posted this to see if you also had any interest in something different.

 > I appreciate the effort tho 😺

Thank you!

**Comment by JetpackDuba** [comment]
> The main thing that was bugging me is that although the idea for the original design is a node-graph, the design itself is a little ambiguous. That is what motivated me to explore some alternatives - especially something non-symmetric because that is what most commit trees look like. To me, the lower rows in the sheet with the 4x and 5x variants not only are immediately recognizable as node graphs, but they are generally more interesting to look at because they don't have symmetry. Your mileage may vary, of course. And come on ... those dark variants just look delicious! 😀


Oh, it's not meant to be a graph as you would expect it in gitnuro, I wanted to have a bit of an artistic take/mix with the idea of a graph and the Premiere Ball from Pokémon (I've always Poke Balls its design :smile: )

![imagen](https://github.com/user-attachments/assets/7a867df6-ff10-40da-aa1f-8aa9c8386aae)


The idea is that Gitnuro has something really good inside, just like the Poké Balls containing Pokémons.

**Comment by priahoud** [comment]
Ok, that explains my confusion then. I roughly know what those are about, but that's it! 😀
It looks like you already have a very specific design in mind, so I will close this ticket.
Thank you for the explanation!
