### ISSUE TITLE
Wrong diff mode when staging single lines of text with windows line endings

### ISSUE THREAD

**Issue by priahoud** [JetpackDuba/Gitnuro#221]
**Describe the bug**
The diff view seems to confuse changes in text files with Windows line endings with image/binary data.
After staging a changed line with a CRLF control character in it, the diff switches to image comparison mode.

**To Reproduce**

1. Create a text file with at least two lines of text. Make sure it has Windows line endings! (CRLF)
2. Stage the whole file
3. Make changes to a line in the file which is followed by another line (e.g. it actually has has a line ending control character)
4. Stage that one line in the diff view

**Expected behavior**
Diff view still displays text data.

**Screencapture**
[Capture.webm](https://github.com/user-attachments/assets/37a595bf-2a86-4991-8435-0f1395fbde57)

**Desktop (please complete the following information):**

- OS: Fedora 40
- Version 1.3.1 https://github.com/JetpackDuba/Gitnuro/commit/e47d4a199e5e470c6821c20803e3a1fad13aa5e0

The same happens on Windows, which is where I encountered this bug  the first time.

**Comment by JetpackDuba** [comment]
Hey! Thanks for the report, I've found the reason and applied a bugfix but I'd like to test it a bit more. The hunks lines didn't remove the \r char at the end of the lines and after staging by line (or hunk) it would add back the line ending, having lines ending in \r\r\n.

I think that's also the same issues as  #213

**Comment by priahoud** [comment]
> Hey! Thanks for the report, I've found the reason and applied a bugfix but I'd like to test it a bit more. The hunks lines didn't remove the \r char at the end of the lines and after staging by line (or hunk) it would add back the line ending, having lines ending in \r\r\n.

That's the stuff in [GetLinesFromTextUseCase.kt](https://github.com/JetpackDuba/Gitnuro/blob/main/src/main/kotlin/com/jetpackduba/gitnuro/git/workspace/GetLinesFromTextUseCase.kt) right? I looked at it yesterday, but couldn't make much sense of the "\n\n" case.

> I think that's also the same issues as #213

Yes, it is! I swear I checked the whole list of bug reports before posting this, but apparently missed that one. Sorry for the double post.

**Comment by JetpackDuba** [comment]
> > Hey! Thanks for the report, I've found the reason and applied a bugfix but I'd like to test it a bit more. The hunks lines didn't remove the \r char at the end of the lines and after staging by line (or hunk) it would add back the line ending, having lines ending in \r\r\n.
> 
> That's the stuff in [GetLinesFromTextUseCase.kt](https://github.com/JetpackDuba/Gitnuro/blob/main/src/main/kotlin/com/jetpackduba/gitnuro/git/workspace/GetLinesFromTextUseCase.kt) right? I looked at it yesterday, but couldn't make much sense of the "\n\n" case.

It's the `lineAt` extension function in `RawTextExtensions.kt`. Apparently jgit's writeline only takes in consideration unix-like line ending, which is quite odd honestly... There are 2 possible solutions: trimming the `\r` char at the end of each line returned in this extensions function or just add a unix-style new line when staging hunks/lines. I think the second one is the best one as it would prevent messing with files that mix different line ending styles (Yes, it's very unlikely but I've seen a couple of cases in the past...)

> > I think that's also the same issues as #213
> 
> Yes, it is! I swear I checked the whole list of bug reports before posting this, but apparently missed that one. Sorry for the double post.

No worries, I'll close them both once it's fixed.

**Comment by priahoud** [comment]
> It's the `lineAt` extension function in `RawTextExtensions.kt`. There are 2 possible solutions: trimming the `\r` char at the end of each line returned in this extensions function or just add a unix-style new line in the `ForamtHunksUseCase`. I think the second one is the best one as it would prevent messing with files that mix different line ending styles (Yes, it's very unlikely but I've seen a couple of cases in the past...)

Hmmm ... unless we talk about only displaying changes in the Application, I think both solutions would be wrong.

> Apparently jgit's writeline only takes in consideration unix-like line ending, which is quite odd honestly... 

As far as I know, jgit behaves the same as cgit. In order to reproduce the original line endings at checkout, the carriage return character must be stored within the commit, which is what see here.

Using the two text lines from the Screencast above in cgit on the cli, freshly staged:

```
$ file test.txt 
test.txt: ASCII text, with CRLF line terminators
```

```diff
$ git diff --cached
diff --git a/test.txt b/test.txt
index e69de29..fa1a9d7 100644
--- a/test.txt
+++ b/test.txt
@@ -0,0 +1,2 @@
+First line^M
+Second line
\ No newline at end of file
```
Notice the "^M" after "+First line" - that is the carriage return character after the transition from the working tree to the index, which is where EOL transformation is supposed to happen in cgit.

To verify that, we do a quick commit ...
```
$ git commit -m "test"
```

... and check the diff ...

```diff
$ git show HEAD
commit c45fa90284dcbe71dda7d9f2f2af413412143ef9 (HEAD -> main)
Author: priahoud <priahoud@posteo.net>
Date:   Sun Aug 11 17:33:02 2024 +0200

    test

diff --git a/test.txt b/test.txt
index e69de29..fa1a9d7 100644
--- a/test.txt
+++ b/test.txt
@@ -0,0 +1,2 @@
+First line^M
+Second line
\ No newline at end of file
```

... and indeed, the carriage return is part of the commit, so it must be filtered out at checkout time for files which are configured to be linefeed only.

**Comment by JetpackDuba** [comment]
> > It's the `lineAt` extension function in `RawTextExtensions.kt`. There are 2 possible solutions: trimming the `\r` char at the end of each line returned in this extensions function or just add a unix-style new line in the `ForamtHunksUseCase`. I think the second one is the best one as it would prevent messing with files that mix different line ending styles (Yes, it's very unlikely but I've seen a couple of cases in the past...)
> 
> Hmmm ... unless we talk about only displaying changes in the Application, I think both solutions would be wrong.

Yes, the solution would be for displaying it properly in the application. However, thanks to your feedback, I digged a bit deeper and found some additional issues with the autoCLRF setting and how text is displayed in Gitnuro, making both solutions quite wrong.

I have a brief idea of how to solve it but not sure if it's feasible, I'll investigate further and let you know.

**Comment by JetpackDuba** [comment]
I've pushed a fix. It has worked with both LF and CRLF as well as multiple autoCRLF configurations. Let me know if the issue still shows up :smile:
