### ISSUE TITLE
[Feature] Push/Pull remote & branch selection

### ISSUE THREAD

**Issue by RichardFevrier** [JetpackDuba/Gitnuro#23]
Correct me if I am wrong but I think when we click on the `push` button Gitnuro tries to push to every remotes.
But when we have multiple remotes, example: _JetpackDuba/Gitnuro_ & _Username/Gitnuro_ we probably just want to push to _Username/Gitnuro_ and create a pull requests for _JetpackDuba/Gitnuro_

So it would be great to have the control over which remote(s) to `push/pull` and also have the control on which branch(es).

Thank you 🙂

**Comment by RichardFevrier** [comment]
I am wrong it does not try to push to every remotes, but that does not discard the fact that having the possibility of choosing would be a great addition 🙂

**Comment by JetpackDuba** [comment]
I've added the option to change the upstream branch of a repository for 1.2. The advanced push/pull options will be delayed to 1.3 because I'm not 100% sure about what does it need, so I'd like to do some research and testing first.
