### ISSUE TITLE
Crash when trying to open specific repo

### ISSUE THREAD

**Issue by aloker** [JetpackDuba/Gitnuro#243]
**Describe the bug**
When I try to open one of my repositories, Gitnuro crashes, the window just closes. This currently only happens for one specific repo, others work just fine.

**To Reproduce**
For copyright reasons, I can´t share the repo publicly, but it's relatively new with not much in it. But when I try to open that repo, the application crashes. Here's a log from the terminal:

```
flatpak run com.jetpackduba.Gitnuro
...
Starting to watch directory /home/ANONYMIZED/projects/ANONYMIZED/ANONYMIZED
thread '<unnamed>' panicked at src/lib.rs:214:1:
Call method [onError] with signature [(I)V] failed with error: Java exception was thrown
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7012b86cdffa - <unknown>
   1:     0x7012b86ef513 - <unknown>
   2:     0x7012b86cb7a3 - <unknown>
   3:     0x7012b86cde42 - <unknown>
   4:     0x7012b86cee37 - <unknown>
   5:     0x7012b86cec66 - <unknown>
   6:     0x7012b86cf407 - <unknown>
   7:     0x7012b86cf266 - <unknown>
   8:     0x7012b86ce4d9 - <unknown>
   9:     0x7012b86cef2c - <unknown>
  10:     0x7012b84764cd - <unknown>
  11:     0x7012b8476562 - <unknown>
  12:     0x7012b8476625 - <unknown>
  13:     0x7012b8486554 - Java_FileWatcherObj_watch
  14:     0x7012dc66c5da - <unknown>
thread caused non-unwinding panic. aborting.
/app/bin/gitnuro: line 2:     3 Aborted                 (core dumped) /app/jre/bin/java -jar /app/share/Gitnuro.jar --flatpak
```

**Expected behavior**
The program should be able to handle this repo, other Git clients can (VS Code, Jetbrains IDEs)

**Desktop (please complete the following information):**

- OS: Linux, Pop OS 22.04, all latest updates
- Version 1.4.0

I know it's not very much information - if there's something I can add to make this more manageable, please let me know.

**Comment by JetpackDuba** [comment]
Hello!

Thank you for your report, apparently when trying to open the repository something goes wrong and Gitnuro doesn't handle the error properly. I've created the milestone 1.4.1 and added the issue to it. If nothing else shows up, I'll create a new release with the fix in the next 2 weeks.

Sorry for the inconviniences.

**Comment by aloker** [comment]
Thanks, this is much appreciated. Let me know if you need anything from me. Keep up the great work, I'm really enjoying Gitnuro

**Comment by JetpackDuba** [comment]
Thank you :smile: 

Are you using the JAR or Flatpak version? I can try to build a JAR for you to test it, but that requires having JDK 17 (or higher) installed. Otherwise, I can try to setup a beta flathub repository.

**Comment by aloker** [comment]
I'm using the flat pack version

**Comment by JetpackDuba** [comment]
Hello,
Sorry for the late answer. Apparently beta.flathub.com has been down for a while and it's not an option... I guess I'll proceed with the release anyway, as the fix it's needed.

It'll be ready during the next few days as I've already pushed a fix in https://github.com/JetpackDuba/Gitnuro/commit/3128341b934bc87f892e4951ec8fa4e4f8d9c3cc

Thank you!
