### ISSUE TITLE
Can not display Japanese commit message

### ISSUE THREAD

**Issue by mrcyclo** [JetpackDuba/Gitnuro#244]
**Describe the bug**
Gitnuro (WSL2) can not display a git commit message in English even I install `language-pack-ja` package.

**To Reproduce**
1. Install WSL2
2. Create a new repo and create a commit message in Japanese, such as "年度末最終週の振替対応"
3. See error

**Expected behavior**
Display a commit message without error

**Screenshots**
![image](https://github.com/user-attachments/assets/2d7fd224-7ebd-4f95-8bb3-a014473390de)

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04 install on WSL2 on Windows 10

**Comment by JetpackDuba** [comment]
Hello!

Honestly, I've got no clue, I know nothing about WSL2. My initial thought is that your installed font is not being used and the built-in font does not support it. I can try to build with a font that support additional languages to see if it improves anything.

Are you using the JAR version?

**Comment by mrcyclo** [comment]
Sorry, my bad. I'm did not installed the right font package.
Problem solved after I run command:
```
sudo apt install fonts-noto-cjk
```

I will close issue for now. Thank you~!
