### ISSUE TITLE
Changing git config removes .gitconfig symlink

### ISSUE THREAD

**Issue by fabiantreu** [JetpackDuba/Gitnuro#245]
**Describe the bug**
I use symlinks to manage my dotfiles. When changing the git config via the Gitnuro GUI (Name and Email), the .gitconfig symlink in my home directory is removed and a normal file is placed there.

**To Reproduce**
Click on "Save data" in the GUI and see how the symlink is replaced with a normal file.

**Expected behavior**
Just edit the file to keep the symlink.

**Desktop:**
- OS: Debian 12 with GNOME
-  Version: 1.4.0

**Comment by JetpackDuba** [comment]
Hello!

I wasn't aware that, fixed! Thank you!
