### ISSUE TITLE
Blog on gitnuro.com is not updated with latest releases

### ISSUE THREAD

**Issue by ruihildt** [JetpackDuba/Gitnuro#247]
When you arrive on the website, it feels like the project is abandoned, since the latest release is from May 2023.

**Comment by JetpackDuba** [comment]
Yes, I'm aware and probably won't be updated because I'm replacing it with a new site. It's ready but just didn't find the time to deploy it.

**Comment by ruihildt** [comment]
Ok thanks, I got a bit confused, an nearly didn't install it because it looked abandoned.

**Comment by riker09** [comment]
> Yes, I'm aware and probably won't be updated because I'm replacing it with a new site. It's ready but just didn't find the time to deploy it.

Is there any way that we (community) can help here?

**Comment by JetpackDuba** [comment]
No worries, just deployed it. Thank you tho!
