### ISSUE TITLE
Pre-commit failure makes commit message disappear

### ISSUE THREAD

**Issue by jelle-it** [JetpackDuba/Gitnuro#248]
**Describe the bug**
I have a pre-commit hook running, so when I press the commit button it runs. When it fails, I get a nice message that my commit failed because of the pre-commit hook. But what is weird is that the commit message goes away. The message however comes back when i switch to another repository and go back.

**To Reproduce**

1. Enable a pre-commit hook
2. Put code in staging that will fail the pre-commit hook
3. Add commit message
4. Press commit
5. Close error popup
6. The message is gone from the commit message box

If you want it back you can follow these steps:
1. Navigate to another tab (repository or New tab)
2. Navigate back
3. The message is restored

**Expected behavior**
The message should not go away at all.

**Screenshots**

https://github.com/user-attachments/assets/51ae4c6c-ddf8-4909-b96a-09ec03d4cccf

**Desktop (please complete the following information):**

- OS: MAC
- Version 1.4.0

**Comment by JetpackDuba** [comment]
Hello,

Good catch, I'll try to have it fixed for the 1.4.1 release (will be released this weekend).

Thank you!
