### ISSUE TITLE
Where config of options!

### ISSUE THREAD

**Issue by asli213312** [JetpackDuba/Gitnuro#254]
**Describe the bug**
Please help me. Im clicked on scale interface 300% and can't find any config with it to restore

**To Reproduce**
select scale interface at 300%

try click on options -_-

**Expected behavior**
click on options

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 1.4.2

**Comment by JetpackDuba** [comment]
Hey,

You can change the ui_scale field by opening the windows registry and going to the following path `HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs/Gitnuro/Config`

**Comment by asli213312** [comment]
Big Thanks!

I've spent a lot of time trying to remove the window expansion limitation in Windows somehow through different programs, but unfortunately none of them helped. This is a really dangerous bug. I really like your app and would like to use it!

**Comment by JetpackDuba** [comment]
You are welcome!

What do you mean by "windows expansion limitation"?

**Comment by asli213312** [comment]
> You are welcome!
> 
> What do you mean by "windows expansion limitation"?

In Windows impossible raise window more than my resolution, even with powerful programms like InqSoft.Window.Scanner, Advanced Window Manager and etc

**Comment by JetpackDuba** [comment]
Oh, I've never thought of it. It's probably a limitation of the Java implementation of the windowing system, I don't think I can do much there :(

**Comment by asli213312** [comment]
> Oh, I've never thought of it. It's probably a limitation of the Java implementation of the windowing system, I don't think I can do much there :(

It's okay! The main problem with it was solved :)
