### ISSUE TITLE
[Feature] Remember last pull/push choice

### ISSUE THREAD

**Issue by fdc263** [JetpackDuba/Gitnuro#27]
After does a forced push, change the icon (or text) of main bar button and next clicks always execute a force push. 
Apply the same behavior for pull button.

**Comment by JetpackDuba** [comment]
Why would you always do a force push? 🤨

I can understand wanting to have pull rebase as the default behavior (it's a planned feature) but not force push.

**Comment by fdc263** [comment]
When work in a branch, is common amend a commit. Then force push is frequently used. 
This is useful to keep fit and clean repo. ¯\_(ツ)_/¯

**Comment by JetpackDuba** [comment]
I understand the issue but having it as the default seems like a dangerous option because it's a destructive operation.

I'm afraid I'll have to reject it. It's preferable to require 1 more click to do a force push if that prevents possible data loss. Better safe than sorry.
