### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by Nohus** [JetpackDuba/Gitnuro#3]
Loading the contents of `Color.kt` from a JSON file instead would enable theming!
I'd love to create a dark theme that is not blue.

**Comment by ProjectInfinity** [comment]
I wouldn't mind some explanation how we can simplify this @JetpackDuba 

I am not a fan of blue theme either so I started work on porting a catppuccin based theme but I discovered quickly that simply adding the theme to the theme list and overriding palette in a call to `darkColors()` was not enough as there were many things that was not possible to override with this function alone. 

If you are able to write a small introduction to how complete theming works in Gitnuro I would be happy to start porting a few themes I have in mind (even if it is baked into the application as opposed to being loaded from a external JSON file. :)

**Comment by JetpackDuba** [comment]
It's a big mess right now, as there isn't an easy way to do it without some refactoring. Not only from a techincal perspective but also UI/UX (there are some inconsistencies in the colors usage from random experimentation which should be fixed to avoid breaking the theming constantly).

I will eventually get into it but not right now. I would like to release the first stable version first and then iterate on it by adding customizations like this one.

In max 2 months it should be done (probably less), so please wait until then 🙂

**Comment by JetpackDuba** [comment]
I'll add some docs later on and some improvements (like notifying when something has gone wrong) but here goes the first version of this.

Load a json from the settings with your desired color scheme like this one:

```
{
    "primary": "FF456b00",
    "primaryVariant": "FF456b00",
    "onPrimary": "FFFFFFFFF",
    "secondary": "FF9c27b0",
    "primaryText": "FF141f00",
    "secondaryText": "FF595858",
    "error": "FFc93838",
    "onError": "FFFFFFFF",
    "background": "FFe7f2d3",
    "backgroundSelected": "C0cee1f2",
    "surface": "FFc5f078",
    "secondarySurface": "FFedeef2",
    "headerBackground": "FFF4F6FA",
    "borderColor": "FF989898",
    "graphHeaderBackground": "FFF4F6FA",
    "addFile": "FF32A852",
    "deletedFile": "FFc93838",
    "modifiedFile": "FF0070D8",
    "conflictingFile": "FFFFB638",
    "dialogOverlay": "AA000000",
    "normalScrollbar": "FFCCCCCC",
    "hoverScrollbar": "FF0070D8"
}
```

Remember to include the alpha, otherwise it will be 0 and everything will be transparent (I'll change it in the future to be opaque by default).
