### ISSUE TITLE
Gitnuro Roadmap

### ISSUE THREAD

**Issue by JetpackDuba** [JetpackDuba/Gitnuro#41]
# Gitnuro roadmap (last update 21/03/2023 DD/MM/YYYY)

## Context

Before release v1.0, Gitnuro was a project meant to cover my needs, without worrying much about the rough edges and the UX in general. After that release, Gitnuro userbase started growing and giving feedback about new features, changes and, of course, reporting bugs. That made me change my mind and focus more in making a product that can be used by anyone, independently of their experience with Git.

I'm currently doing a research to improve Gitnuro's user experience as well as evaluating which features are the most relevant and how to prioritize them but, as already explained in the FAQ, Gitnuro does not make use of any kind of data collection to understand the users' behavior, which means that I'm counting on you (the users) to share your experience and issues with Gitnuro, your feedback is important so we can make a better product for everyone.

## 1.3.0 Roadmap

There isn't a release date planned yet. 

This release will include some customization options as well as keep adding new features. This list will be expanded after v1.2.

- https://github.com/JetpackDuba/Gitnuro/issues/39
- https://github.com/JetpackDuba/Gitnuro/issues/40
- https://github.com/JetpackDuba/Gitnuro/issues/10
- https://github.com/JetpackDuba/Gitnuro/issues/37
- https://github.com/JetpackDuba/Gitnuro/issues/38
- https://github.com/JetpackDuba/Gitnuro/issues/42
- WIP

Previous versions:
## 1.2.0 Roadmap

This version will be focused mainly in improving the SSH authentication (as much possible),  add support to submodules and complete the UI/UX design. This last point includes better integration with the keyboard, clearer errors messages.

Main tasks for this version:
- https://github.com/JetpackDuba/Gitnuro/issues/32
- https://github.com/JetpackDuba/Gitnuro/issues/29
- https://github.com/JetpackDuba/Gitnuro/issues/28
- https://github.com/JetpackDuba/Gitnuro/issues/33
- https://github.com/JetpackDuba/Gitnuro/issues/21
- https://github.com/JetpackDuba/Gitnuro/issues/34
- https://github.com/JetpackDuba/Gitnuro/issues/35
- https://github.com/JetpackDuba/Gitnuro/issues/23
- https://github.com/JetpackDuba/Gitnuro/issues/26
- https://github.com/JetpackDuba/Gitnuro/issues/43
- https://github.com/JetpackDuba/Gitnuro/issues/44
- https://github.com/JetpackDuba/Gitnuro/issues/45
- https://github.com/JetpackDuba/Gitnuro/issues/36

**Comment by nishpatel77** [comment]
Hi @JetpackDuba  I love this project, never knew about multiplatform for kotlin plus the UI, lots of stuff I need to learn... Hoping to learn more and contribute on the features.

**Comment by nishp77** [comment]
Hi @JetpackDuba I found this project 2 days back because gitkraken has licensing issue with the current company I work at. I love this that kotlin had this, like haven't been following. I would like to contribute, wanna learn lot on multipaltform side

**Comment by JetpackDuba** [comment]
Thanks for your interest :smile: 

Feel free to open PR or ask whatever you need.

**Comment by nishp77** [comment]
I wanna ask you question regarding the UI of the app, looks very similar to GitKraken. However we could tweak something for the UI side

**Comment by JetpackDuba** [comment]
I'm aware of the similitude with Gitkraken, as they've got a really nice UI, but extremly saturated of less useful stuff imo. In other ways, I like their base layout divided in 3 main columns but I don't like their implementation.

There are quite some changes that I'll slowly introduce, I've already got a prototype designed (not fully finished but almost) but it's not a high priority task tho, as it requires a considerable amount of work. An example would be having the option to have the option to move the "uncommited changes"/"commit changes" to the bottom, similar to other Git clients, as it works better when splitting the screen in half or using 4:3 displays.

The idea would be to give the user some freedom to adapt the UI to their needs, but it requires some refactoring of the current code.

**Comment by workhard-getvinfast** [comment]
I love this app experience but it quite missing some feature, like directly ignore file option. Maybe I will plan to contribute some stuffs.

**Comment by JetpackDuba** [comment]
Hey @workhard-getvinfast ! Feel free to open an issue and I may try to add it in a future release :smile: 

Features are added depending on how important or requested are, so give a thumbs up :+1:  to the issues you are most interested in getting done, as I tend to give priority to the most _upvoted_.
