### ISSUE TITLE
Search of branches, tags, remotes & stashes

### ISSUE THREAD

**Issue by JetpackDuba** [JetpackDuba/Gitnuro#43]
Side panel should include a field to filter and quickly search between different types of references

**Comment by aguragorn** [comment]
Hey @JetpackDuba, can you share more info on the changes needed so we can get a better implementation of this feature? I'm interested in working on this feature

**Comment by JetpackDuba** [comment]
Hey!

I ended up doing a quick refactor + implementation of it after closing your PR. It's not fully tested but should work fine.

I'll push it in a moment if you want to take a look at it. It's nice that it filters stuff without having to reload the data in the repository by chaining the flows.
