### ISSUE TITLE
Add support for singning commits with gpg

### ISSUE THREAD

**Issue by Seil0** [JetpackDuba/Gitnuro#45]
As a user I want to sing my commits with a GPG key.

### Expected behaviour:
Gitnuro signs my commits with the configured GPG key.

### Actual behaviour
Gitnuro fails to sing the commit with error "Signing service is not available".

### Possible solution
Add org.eclipse.jgit:org.eclipse.jgit.gpg.bc to support signing commits.
Note: org.eclipse.jgit.gpg.bc will increase the compiled file/jar size considerably, see: https://wiki.eclipse.org/JGit/New_and_Noteworthy/5.8#GPG

**Comment by JetpackDuba** [comment]
Noted!

I'll try to see if adding proguard may reduce the file increase in the resulting binaries.

**Comment by OdinVex** [comment]
The ability to signoff would also be nice (unrelated to GPG, but similar).

**Comment by JetpackDuba** [comment]
Hey @OdinVex , thanks for you suggestion! Can you please create another issue for such feature, please? So it's easier to keep track of it.

**Comment by OdinVex** [comment]
> Hey @OdinVex , thanks for you suggestion! Can you please create another issue for such feature, please? So it's easier to keep track of it.

Certainly. :)

**Comment by JetpackDuba** [comment]
I'm reopening it since I've found a couple of issues when rebasing.

**Comment by gabeklavans** [comment]
Hi,

My gitconfig has the `gpg.format=ssh`, as I use 1Password (`gpg.ssh.program=C:\...\op-ssh-sign.exe`) to sign my commits with an SSH key. However, it seems that Gitnuro errors out when I try to make commits:
```
Invalid value: gpg.format=ssh
```

I believe adding support for other gpg formats would be part of this request.
