### ISSUE TITLE
add repository registry to left side

### ISSUE THREAD

**Issue by long76** [JetpackDuba/Gitnuro#49]
**Is your feature request related to a problem? Please describe.**
if i have many repos now i must keep open all or reopen from recent/readd from file manager

**Describe the solution you'd like**
Repository registry like in TortoiseHG, tabs = openned repos
![Screenshot+from+2014-05-11+00_51_12](https://user-images.githubusercontent.com/18124433/203714443-f0745479-7e90-4672-90e8-a9b60d8b58d9.png)

**Comment by JetpackDuba** [comment]
Not really sure of what's the benefit of this. It takes waaaaay too much horizontal space to get almost the same behavior.

**Comment by long76** [comment]
> Not really sure of what's the benefit of this. It takes waaaaay too much horizontal space to get almost the same behavior.

what about made registry like toggle panel from left? open panel open needed projects hide panel

**Comment by long76** [comment]
just i have 53 repo) how i can see all of them and open needed? now i need reopen needed repositories it's not comfortable)

**Comment by JetpackDuba** [comment]
Removing the limit in the recent repositories and adding a search field is an option (which is something I've been thinking about) . Would that be good enough?

Doing something similar to the image is out of question, as it's something really niche that most users won't find useful in most cases. The "open" button in the next release will show the recent repositories which should make things even easier.

**Comment by JetpackDuba** [comment]
Not sure if there is anything else to discuss, as there is no intention to include such feature. Let me know if there is anything else to discuss.

**Comment by ProjectInfinity** [comment]
What about a "workspace" overview like this
![image](https://github.com/JetpackDuba/Gitnuro/assets/593870/7bf37e8a-a4a3-4336-a275-ddb67abb5b55)

Though expanding recent list and allowing you to search it would probably cover my use-case as well.

**Comment by MetalArend** [comment]
> Removing the limit in the recent repositories and adding a search field is an option (which is something I've been thinking about) . Would that be good enough?
> 
> Doing something similar to the image is out of question, as it's something really niche that most users won't find useful in most cases. The "open" button in one of the next releases will show the recent repositories which should make things even easier.

The trouble with "recent repositories" is that it will probably never have the possibilities one would expect in a bookmark pane. An example of a use case: we have a client, who have a few closely related repositories. I'm mostly working on one of those repositories, but whenever I have to switch to one of the less used repositories, I get to search my disk again for the other repositories. In a pane, I could some day sort them the way I like them sorted, maybe even group them.

**Comment by JetpackDuba** [comment]
I could consider having a list of pinned list of repositories or something similar to what @ProjectInfinity suggested. I'm open for alternative proposals that do not involve changing the current layout of the repository view.

**Comment by karlwilbur** [comment]
I have a similar issue where I have about 25-30 repos that I am constantly hoping around from one to another. I don't feel like I need to keep them all open in tabs all the time; I don't mind closing tabs adn re-opening them as needed. However, having to look them up on the filesystem each time is a pain. I would think something like a "Recent" list a little lager than 10 would help me. Maybe a config option to allow `AppStateManager::repositoryTabChanged` to handle more than 10 recent repos on the Welcome/New tab page:

https://github.com/JetpackDuba/Gitnuro/blob/38867ebb070fc36a55bc3836f7ff0587abcd27f8/src/main/kotlin/com/jetpackduba/gitnuro/managers/AppStateManager.kt#L39

Of course there would still need to be a limit; 100 repos might just blow the rendered layout apart. Maybe something like a search option on the Welcome/New tab page?  It could search a larger list while still only showing the 10 most recent in the layout.

> Removing the limit in the recent repositories and adding a search field is an option (which is something I've been thinking about) . Would that be good enough?


So, yeah, I think that would be a good solution.

**Comment by JetpackDuba** [comment]
I had some kind of prototype lying around so I decided to finish it. I think this solves most of the pain points mentioned in this issue.

Welcome page:

![Captura desde 2024-06-15 17-38-37](https://github.com/JetpackDuba/Gitnuro/assets/16917468/f4544ac8-a1c5-40ac-8475-c6400c39ab71)

New popup when clicking on "Open":
![image_2024-06-18_13-23-39](https://github.com/JetpackDuba/Gitnuro/assets/16917468/56dc0762-8f5f-4faa-8305-70fa3b0ca621)

The UI/UX is still WIP but I think that would make it much easier to switch between repositories.

**Comment by karlwilbur** [comment]
I just installed version 1.4.0. This is great! Thank you. The only thing I would change is that I would like the repos alpha sorted but having them sort by most recent makes more sense, perhaps, for a list of _recent_ repos. The search make lookups trivial such that sort order is practically irrelevant. 

Thanks again. This is a real quality-of-life improvement.
