### ISSUE TITLE
Write commit message at awrong korean lang Text at Double inputs that's space_bar

### ISSUE THREAD

**Issue by sjin9696** [JetpackDuba/Gitnuro#50]
**Describe the bug**
Hi. sorry. im very little english.. T_T
Hi. That's Bug report.
: korean lang Text at Double inputs

**To Reproduce**
1. Go to 'Writing to korea langs at Commit message'
2. Click on ' no click, take keyboard at spacebar'
3. Scroll down to 'no scroll down'
4. See error 'Last Words thats double inputs, "입력-> 입력력"

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59603332/204744465-5ae9c468-831c-4638-9e2c-957e0d9eecc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Version 19044.2251

**Comment by JetpackDuba** [comment]
Hey!
> im very little english.. T_T

No worries :smile: 

I'm not familiar with Korean but I'll try to reproduce it.

**Comment by JetpackDuba** [comment]
Sorry for the late answer, it seems that it was a [Compose issue](https://github.com/JetBrains/compose-multiplatform-core/pull/406). It should be fixed on the next  release.
