### ISSUE TITLE
Open repository from command line

### ISSUE THREAD

**Issue by giflw** [JetpackDuba/Gitnuro#51]
**Is your feature request related to a problem? Please describe.**
I want to be able to open a git repository from command line, like:

```
gitnuro .
gitnuro path/to/repo
```

**Describe the solution you'd like**
Gitnuro opens given repository as active tab on UI

**Describe alternatives you've considered**
No one for now

**Additional context**
I use command line a lot, and is almost always more efficient to me to just type a new command to open a GUI application

**Comment by JetpackDuba** [comment]
I've wanted to have it for a while. I'll add it in 1.2.0 for sure!

**Comment by nean-0** [comment]
It's marked as completed as of 1.2.0. I have 1.2.1 installed.

How is it supposed to work? 

I tried (with a repo in the current direcory):

'com.jetpackduba.Gitnuro .'
'com.jetpackduba.Gitnuro $PWD'
'flatpak run --branch=stable --arch=aarch64 com.jetpackduba.Gitnuro $PWD'

No matter how, it only opens the main window and never the repo when Gitnuro launches.

Should there be some switch preceding the directory name?

**Comment by JetpackDuba** [comment]
It's probably because the flatpak version uses a script which does not pass the arguments to gitnuro, ugh. Can you please open an issue in https://github.com/flathub/com.jetpackduba.Gitnuro ?

**Comment by nean-0** [comment]
OK, I did.
