### ISSUE TITLE
using jreleaser

### ISSUE THREAD

**Issue by pdefert** [JetpackDuba/Gitnuro#52]
do you plan  to use https://jreleaser.org/ for release and delivery ?
you can produce OS packaging , and native version

**Comment by JetpackDuba** [comment]
What would be the beneffit of doing so? I'm not familiar with it but I can't really see the beneffit of switching to it, as it seems to only be useful for Homebrew releases.

**Comment by JetpackDuba** [comment]
I'll close the issue for now, let me know if I'm missing something to reopen it.

**Comment by aalmiray** [comment]
Well, JReleaser it's not only useful for publishing Homebrew forlumae, but also other packagers. The full list can be seen at https://jreleaser.org/guide/latest/integrations.html#_package_publish

Besides, it can also tag and create a Git release with auto-generated release notes (or include an external file), as well as announcing a release to multiple channels.

**Comment by JetpackDuba** [comment]
> Well, JReleaser it's not only useful for publishing Homebrew forlumae, but also other packagers. The full list can be seen at https://jreleaser.org/guide/latest/integrations.html#_package_publish

Yeah, I'm aware, however, I'm only interested in homebrew and Flatpak, which take me no more than 5min to deploy. I'm not really interested in the rest of features or packagers.
