### ISSUE TITLE
Predefined commit messages

### ISSUE THREAD

**Issue by earthjasonlin** [JetpackDuba/Gitnuro#54]
It will be better if there is a button that opens a list to let user select a predefined message in settings next to the "Commit", and support some variables such as date, time, changed file names or something like that

**Comment by JetpackDuba** [comment]
Hey! Sorry for getting back so late.

What would be the benefit of such feature? Date/time and changed file names are part of the commit, wouldn't make much sense to have it in the message.

**Comment by adam-ce** [comment]
git cola has a very nice commit system in my opinion. they have a list of previous messages (that i sometimes use), fixup! previous commit message, spellchecker, and imho a better amend ui (you click on amend, it loads the previous commit message, and shows the changes from the amended commit as staged. you can then add or remove stuff from the stage area).

**Comment by JetpackDuba** [comment]
> git cola has a very nice commit system in my opinion. they have a list of previous messages (that i sometimes use), fixup! previous commit message, spellchecker, and imho a better amend ui (you click on amend, it loads the previous commit message, and shows the changes from the amended commit as staged. you can then add or remove stuff from the stage area).

Sorry, I missed your comment. The amend ui was changed but the rest of suggestions are not. Feel free to open a new issue to discuss the other points.

As for the issue itself, I'll close it due to the lack of response.
