### ISSUE TITLE
Ctrl+Backspace Crashes

### ISSUE THREAD

**Issue by aiquiti** [JetpackDuba/Gitnuro#55]
When changing your name/email you can crash the program by pressing CTRL+Backspace (shortcut for deleting whole word). That is all that is needed to reproduce error. Simply backspacing does not reproduce error.

![image](https://user-images.githubusercontent.com/57577669/207399939-343265ca-d02c-4ad6-8a4d-81c2e809a2bf.png)
_(alt: Error: offset(-1) is out of bounds [0, 0])_

**Comment by JetpackDuba** [comment]
Hey! Thanks for your report @aiquiti 

Yeah, it's a known issue in compose, will be fixed for the next release. It only happens when you ctrl+backspace with an empty field. More info here https://github.com/JetBrains/compose-jb/issues/2466

**Comment by JetpackDuba** [comment]
Updating compose dependency has fixed the issue, the fix will be available in Gitnuro v1.2.0.
