### ISSUE TITLE
Show full repo name in tab

### ISSUE THREAD

**Issue by aphu** [JetpackDuba/Gitnuro#56]
**Is your feature request related to a problem? Please describe.**
It would be nice to show the full repo name in a tab instead of it being cutoff.

**Comment by JetpackDuba** [comment]
Hey! Thanks for your feedback @aphu 

I've planned a few changes related to this and also the option to see the path of each repository. I'll give more details about it in the near future.

**Comment by JetpackDuba** [comment]
Hey! Gitnuro now accepts longer tabs, up to ~700dp (dp = px * scaling ratio). Also hovering on the tab itself will show the full path of that repository as shown in the following image:

![image](https://user-images.githubusercontent.com/16917468/231890725-2704aa19-c6ae-45ea-b6fa-81146c60dffb.png)

It'll be part of release 1.2.0, which should be released in about 1-2 weeks.
