### ISSUE TITLE
The file browser dialog is seems to be broken on macOS

### ISSUE THREAD

**Issue by taranlu-houzz** [JetpackDuba/Gitnuro#57]
**Describe the bug**
The file browser does not allow navigating the file system at all.

**To Reproduce**
1. Open the app.
2. Click "Open a repository."
3. Try to navigate into any of the folders listed by double clicking on them (nothing happens).
4. Seems that theming is also pretty broken (highlighting and colors are odd).

**Expected behavior**
Might be better to have the native macOS file browser dialog?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.6.1 (21G217)
 - `gitnuro` installed via `brew`

**Comment by JetpackDuba** [comment]
Hello! Thanks for your report @taranlu-houzz 

Can you record a video to show the behavior? Or at least a screenshot.

I've only tested it with a VM (I haven't got a MacOS pc) and worked fine.

**Comment by taranlu-houzz** [comment]
Hey @JetpackDuba, here is a screenshot:
![Screen Shot 2022-12-15 at 12 29 24](https://user-images.githubusercontent.com/52425255/207961353-29c21e1f-ade4-4959-bccb-ccbd099fd268.png)

The red was added for privacy, but essentially, I am unable to navigate through the file system by clicking (or double clicking) on any of the folders.

**Comment by JetpackDuba** [comment]
That's... weird. Is it intel or arm? I'll ask a friend to test and let you know asap.

**Comment by taranlu-houzz** [comment]
This is a 2019 Intel MacBook Pro. Interestingly, there are a lot of aspects about the dialogue that are broken:

- Clicking on folders does highlight them and causes the "Choose" button to activate, but double clicking does not navigate into the directory.
- Weird styling/theming issues:
  - The black bar in the screenshot seems odd.
  - The currently selected highlighted option in the dropdown menus ends up being white on white, so it is very hard to see.
- If I use the top dropdown, I am able to navigate up to a different folder (I always seem to be in `~/Documents` by default).

Thanks for getting back to me on this! I am looking for a replacement for `ungit`, mainly for quick and clear visualization of the git graph, and `gitnuro` is an intriguing option.

**Comment by JetpackDuba** [comment]
A friend has done a few tests and worked fine with the same OS and also an intel CPU. 

I can try to use a different file dialog API and ask you to test the built package if you are willing to.

**Comment by ProjectInfinity** [comment]
I've tested a fix, by using java.awt.FileDialog it uses the native filepicker instead of the JFileChooser one which doesn't look native.

Is there a reason for us to not use this for all operating systems (or maybe not for linux as it seems it has a separate implementation)? JFileChooser is kinda ancient and doesn't respect modern settings like themeing.

**Comment by JetpackDuba** [comment]
It had some issues when using it as a Directory picker.

**Comment by ProjectInfinity** [comment]
On Mac? It worked fine in my testing. What didn't work?

**Comment by JetpackDuba** [comment]
On windows & linux. I don't remember exactly tho. I think that you couldn't pick directories, only files. I'll take a look into the pr in a bit

**Comment by ProjectInfinity** [comment]
Aha ok that's what I was afraid of so I limited by PR to macOS only because Apple exposes a property that seems to handle it picking directories only. :)

` System.setProperty("apple.awt.fileDialogForDirectories", "true")`

**Comment by taranlu-houzz** [comment]
@JetpackDuba @ProjectInfinity Hey, thanks for looking into this, much appreciated! I'm currently on winter vacation, but I will check this thread every now and then and would be glad to try to test out a patch if need be.

**Comment by JetpackDuba** [comment]
Sorry for my late answer. I'll finish my master's thesis in 2 weeks, after that I'll take a look if it's possible to use the native MacOS API instead of relying on the swing implementation as it's done currently.

**Comment by JetpackDuba** [comment]
@taranlu-houzz  can you please give it another try with Gitnuro 1.2.0? It includes the fix from @ProjectInfinity
