### ISSUE TITLE
[Feature Request] Automatic Signoff Support

### ISSUE THREAD

**Issue by OdinVex** [JetpackDuba/Gitnuro#60]
**Describe the solution you'd like**
The ability to use Git's automatic Signoff feature would be nice, it helps to keep track of committers.

**Additional context**
See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff for more information.
Some environments *require* this kind of behavior.

**Comment by JetpackDuba** [comment]
Thanks! I'll look into it.

**Comment by OdinVex** [comment]
I don't know how Gitnuro interacts with Git (such as libgit2, or shell), but it is a simple `-s` appended to any `git commit` command.

**Comment by JetpackDuba** [comment]
It uses JGit. It has a few methods related to signing but I haven't tried them yet.

**Comment by OdinVex** [comment]
> It uses JGit. It has a few methods related to signing but I haven't tried them yet.

A very quick glance as JGit revealed nothing in the way of adding a sign-off. Basically, git will automatically add this to the end of commit messages: `Signed-off-by: User Name <user.name@example.fqdn>
`. It is used to [help prevent lawsuits](https://stackoverflow.com/a/1962112).

**Comment by JetpackDuba** [comment]
I see. Should be fairly easy to simply add it at the end of the message.

I've got a few questions about it though:

1. Do you use it in every repository or just specific ones?
1. Is every commit signed or just specific ones?

The context can be useful so I can have a better idea about how to implement.

**Comment by OdinVex** [comment]
You can use sign-off on any/all commits, regardless of GPG status. It's best to think of it as a 'macro' that simply appends a signed-off-by text. You can use such functionality on any repo or all. I usually issue git commits such as:

```
git commit -S -s -m "Add Exit Handling" -m "Added catching dialogues to prevent accidental Alt+F4/Window-Closing"
```
(-S = gpgsign, -s = signoff, ...)

Final Git Message contents:
```
Add Exit Handling

Added catching dialogues to prevent accidental Alt+F4/Window-Closing

Signed-off-by: User Name <user.name@example.fqdn>
```

Some repos on [GitHub](https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/) can even *require* them before a commit will even push.

**Comment by JetpackDuba** [comment]
Thanks for the detailed explanation :smile: 

I'll think about how to implement it, as I'd like to have it for v1.2.

**Comment by JetpackDuba** [comment]
Yeah, I was thinking more about how to add it to the UI mostly, the implementation itself should be easy

**Comment by JetpackDuba** [comment]
Hello!

I've added an option under "Action" to configure the signoff at repository level. Ideally this should be in the settings screen, but the settings are for now restricted only to global settings.

In the future I'll have a dedicated screen for repository-level settings and the signoff settings will be moved there.

 
![imagen](https://user-images.githubusercontent.com/16917468/235466414-e97bef66-337d-43b3-86fb-d5e69928a819.png)
