### ISSUE TITLE
Feature to copy a commit's ID or message to clipboard

### ISSUE THREAD

**Issue by Philipp91** [JetpackDuba/Gitnuro#62]
**Describe the solution you'd like**

In the context menu of a commit (where it currently says "Checkout commit", "Create branch", ...), I'd like to see "Copy Commit SHA" (or "Copy Commit ID") and "Copy Commit Message", which are well-known features from other Git GUIs.

**Describe alternatives you've considered**

`git log` works on CLI, I guess.

**Additional context**

Useful in subsequent commands like amending commits, cherry-picking etc. (even if those features aren't implemented in the Gitnuro UI _yet_).

**Comment by JetpackDuba** [comment]
You can copy de ID by clicking on it in the commit's detail. I don't really want to clutter more the context menu, as it's still missing some entries and it may get too big.

**Comment by JetpackDuba** [comment]
I think there isn't anything to do as this feature is already present as mentioned previously. Closing it, if I'm missing something, please let me know.
