### ISSUE TITLE
Allow editing the commit message when amending

### ISSUE THREAD

**Issue by Philipp91** [JetpackDuba/Gitnuro#63]
**Is your feature request related to a problem? Please describe.**

When I click "Amend previous commit", it commits already. In order to change the commit message, have to copy it manually (currently from CLI `git show`, but see #62) to the message window and edit it there.

**Describe the solution you'd like**

I'd like for the "Amend previous commit" menu item to _not_ commit immediately, but instead:
* copy the previous commit's message into the text field (for editing) and
* change the main "Commit" button's label to "Amend", which then executes the action and goes back to non-amend mode.
* Also the menu item should become "Don't amend" in order to go back to regular committing.

Note that users who _don't_ want to edit the message just have to do one additional click, so not a big pain point.

**Describe alternatives you've considered**

* When clicking "Amend previous commit", it could open a pop-up for editing the message.
* Another menu item "Amend previous commit with different message" that opens the pop-up, whereas the regular "Amend previous commit" menu item doesn't.

But pop-ups and many menu items with long titles are ugly, hence the preferred solution above.

**Additional context**

It then becomes analogous to `git commit --amend`, which also allows editing the message by default.

**Comment by JetpackDuba** [comment]
I've planned to add some kind of checkbox that will automatically fill the message field, but I have to think about it because it'll also have to integrate with other features like #60
