### ISSUE TITLE
Warning message when doing an interactive rebase on the latest commit

### ISSUE THREAD

**Issue by Philipp91** [JetpackDuba/Gitnuro#64]
**Describe the bug**

I discovered the "Interactive rebase" feature in the context menu but wasn't sure how it worked.

**To Reproduce**

1. Open the commit log view.
2. Right-click the first commit.
3. Pick the "Interactive rebase" menu item.
4. Observe that nothing happens. That's weird.

**Expected behavior**

Either the menu item shouldn't even exist (as it doesn't make sense to rebase on top of the top-most commit). Or (preferred, due to its advertisement value) the application should show a warning dialog to explain that users should issue the "Interactive rebase" action on the bottom-most commit of the stack they want to operate on.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: head

**Comment by JetpackDuba** [comment]
Yeah, it should be hidden. Thanks for pointing it out.
