### ISSUE TITLE
More commit handling options during interactive rebase

### ISSUE THREAD

**Issue by Philipp91** [JetpackDuba/Gitnuro#65]
**Is your feature request related to a problem? Please describe.**

Interactive rebase currently offers "Pick" and "Reword" for the top-most commit, and additionally "Squash" and "Fixup" for the subsequent ones.

**Describe the solution you'd like**

I'd also like:
* "Edit" (allowing to change the commit's contents and not just its message)
* "Drop" (i.e. not using the commit at all, useful when assembling pull requests with partial changes)

**Describe alternatives you've considered**

CLI [supports those](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history).

**Comment by JetpackDuba** [comment]
Hey!

Drop is not supported by JGit currently. Edit I'll try to do it in the future but is not prioritary, as I'm planning to do some changes to the rebase interactive implementation.

**Comment by Philipp91** [comment]
Drop is supported implicitly, by removing the `RebaseTodoLine` entirely from the `List` passed into `prepareSteps()`.

**Comment by Philipp91** [comment]
Btw I'm generally happy to contribute some changes, though I won't by default as you seem to be developing actively (" I'm planning to do some changes to the rebase interactive implementation.") and I don't want to risk larger merge conflicts / incompatible UI ideas.

**Comment by JetpackDuba** [comment]
> Drop is supported implicitly, by removing the `RebaseTodoLine` entirely from the `List` passed into `prepareSteps()`.

Ah damn, wasn't aware of that! Thanks for the explanation.



> Btw I'm generally happy to contribute some changes, though I won't by default as you seem to be developing actively (" I'm planning to do some changes to the rebase interactive implementation.") and I don't want to risk larger merge conflicts / incompatible UI ideas.

Being honest, I'd love if you keep sharing ideas or bug reports so I can keep improving the product. Fortunetaly I don't need much help right now in terms of coding but I want to get as much feedback as possible to improve the UX :smile: .
