### ISSUE TITLE
Build app and run tests on GitHub (CI and PRs)

### ISSUE THREAD

**Issue by Philipp91** [JetpackDuba/Gitnuro#67]
Tests are currently broken and apparently this wasn't noticed. Running tests automatically (with Travis? with GitHub Actions?) on a regular basis as well as for every pull request should prevent such issues in future.

**Comment by JetpackDuba** [comment]
Yeah, tests have to be recreated from scratch, there is an issue open for it https://github.com/JetpackDuba/Gitnuro/issues/35

About the CI... Not a priority currently. Once the tests are fixed I may do it but not for now.

**Comment by JetpackDuba** [comment]
Actually, I've taken a look at GitHub Actions and it's easier than I was expecting. I've got a little trauma with jenkins, ngl. I'll take a look into it after the libssh integration, since it'll require to build the native libs for each platform.
