### ISSUE TITLE
Save HTTP authentication credentials

### ISSUE THREAD

**Issue by Flashdown** [JetpackDuba/Gitnuro#75]
**Is your feature request related to a problem? Please describe.**
I need to reenter my user and password for every pull and push action.

**Describe the solution you'd like**
Stay logged in until login session/cookie expires

**Comment by JetpackDuba** [comment]
There are plans to preserve the login credentials in-memory but not sure for when. Cookies don't make any sense in this context.

I'd recommend using SSH or Git Credentials Manager.

**Comment by Flashdown** [comment]
Is it really needed to store the password in memory? 

I have really no clue about Kotlin, just to be clear, but you do HTTP authentication, so you are acting as a HTTP client in this scenario, so should'nt it be possible to just pass the creds to the web server for session creation (first HTTP transaction) and store the session ID from the HTTP response instead and reuse it for future transactions until the webserver invalidates the session and forces one to relogin?

I have googled a bit about Kotlin and how to manage HTTP requests in there and I've found a section about khttp **7.1. Handling Headers and Cookies** https://www.baeldung.com/kotlin/khttp#headers-cookies

This appears to me that khttp might support this way. What do you think?

**Comment by JetpackDuba** [comment]
In one hand, I don't handle the HTTP authentication but JGit does, it's not something that I can manipulate.

In the other hand, doing something like that would be server specific and it wouldn't work in all cases as each Git server can have a different implementation. Usually the credentials are passed everytime you interact with the server. Git CLI works the same way unless you play with [httpcookieFile](https://git-scm.com/docs/git-config#Documentation/git-config.txt-httpcookieFile), which is not common at all. I'm not even sure if GitHub and GitLab support such thing.

So as for now, keeping the credentials in memory would be the easiest way to make it work with any Git server. The credentials would only be asked once each time you open Gitnuro or a tab. If that's not an option, I'd try Git Credentials Manager, which main goal is to simplify all that stuff.

**Comment by Flashdown** [comment]
I see, thank you, also for creating Gitnuro and it's nice UI. :)

**Comment by JetpackDuba** [comment]
I've been recently working on this feature but I'm not really sure about how to manage it.

There are 2 possibilities:
1. Storing credentials in-memory until Gitnuro is restarted.
1. Persist them in a password-protected file, as if it was a password manager. This would be the best option but also the one which has more security concerns as well as complexity. So the previous option is probably better for now.

Have you got any additional suggestions? :smile:

**Comment by Flashdown** [comment]
hehe, you've asked, here it comes ^^:

First of all I think it should become a setting of Gitnuro to define how long the password is cached, maybe in hours ?. The default should be to store it until Gitnuro is closed which should be represented with a value of 0 but I think also 0.XX should be supported to be able to define values representing less than an hour, too.

I prefer to store a given password in memory, but encrypted, that is beeing decrypted on demand only and any temp vars used during decryption should be cleared. So let my try to visualise this flow.

Gitnuro startup -> Create a new random encryption key that is only used during the lifetime of this Gitnuro instance :)
"Password Given" -> Password is beeing encrypted, all used variables are cleared except encrypted user password and our random encryption key that we've created during startup.
"Password Needed" -> Use encryption key to decode the pw where needed, ensure temp vars are cleared.

As you know Kotlin is none of my languages, but I've searched a bit to find code that represents the way I would like to see the encryption/decryption process working and this looks like it could fit the bill:

Quoted code below is copied from here: https://stackoverflow.com/questions/49340005/encrypt-decrypt-string-kotlin/62660171#62660171
`const val encryptionKey = "ENCRYPTION_KEY"

fun String.cipherEncrypt(encryptionKey: String): String? {
    try {
        val secretKeySpec = SecretKeySpec(encryptionKey.toByteArray(), "AES")
        val iv = encryptionKey.toByteArray()
        val ivParameterSpec = IvParameterSpec(iv)

        val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
        cipher.init(Cipher.ENCRYPT_MODE, secretKeySpec, ivParameterSpec)

        val encryptedValue = cipher.doFinal(this.toByteArray())
        return Base64.encodeToString(encryptedValue, Base64.DEFAULT)
    } catch (e: Exception) {
        e.message?.let{ Log.e("encryptor", it) }
    }
    return null
}

fun String.cipherDecrypt(encryptionKey: String): String? {
    try {
        val secretKeySpec = SecretKeySpec(encryptionKey.toByteArray(), "AES")
        val iv = encryptionKey.toByteArray()
        val ivParameterSpec = IvParameterSpec(iv)

        val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
        cipher.init(Cipher.DECRYPT_MODE, secretKeySpec, ivParameterSpec)

        val decodedValue = Base64.decode(this, Base64.DEFAULT)
        val decryptedValue = cipher.doFinal(decodedValue)
        return String(decryptedValue)
    } catch (e: Exception) {
        e.message?.let{ Log.e("decryptor", it) }
    }
    return null
}`

**Comment by JetpackDuba** [comment]
Sorry for the late response, took some days off :)

Thanks for your sharing your thoughts :smile:  It's quite similar to what I was thinking! Encrypting can be an interesting measure. I've got to read more about how effective it is in the JVM world, in case there are other alternatives.

> First of all I think it should become a setting of Gitnuro to define how long the password is cached, maybe in hours ?. The default should be to store it until Gitnuro is closed which should be represented with a value of 0 but I think also 0.XX should be supported to be able to define values representing less than an hour, too.

I'm not sure about the expiration time of the data. I like the concept but not sure about the implementation. I think that having a dropdown with some reasonable predefined values would be nicer. An example could be:

- Until restart
- 15 minutes
- 1 hour
- 4 hours
- 8 hours

I may open a different issue for this and for now having "until restart" as the default behavior, so I can get feedback of the main feature first to keep it as simple as possible. I'll have to consider it.

**Comment by Flashdown** [comment]
Hi, was traveling for some weeks, I think your idea regarding the expiration times chooseable are most probably sufficient for everyone and looks indeed more friendly than my approach ^^ and I think we can skip another issue for that, as users anyway will create one once one find it doesnt fit their needs/ use-case. :)

**Comment by JetpackDuba** [comment]
I've implemented the feature, thanks for you valuable feedback :smile:  It will be available in the next release (should be release in about 1 month).

Thank you :smile:

**Comment by Laconiccrusader** [comment]
@JetpackDuba I'm having issues with caching HTTP credentials in 1.3.1, should I comment here or open a new issue?

**Comment by JetpackDuba** [comment]
Feel free to create a new issue :+1:

**Comment by Flashdown** [comment]
Actually the issue seems to be about the length check of the random created encryption key, I think as soon as one of the special characters I added is part of the encryption string, then the length check is not matching it correctly. A workaround is to close and start Gitnuro until the random string is without special chars. Maybe we need to change the length check to check if the string is matching the expected length or is a little longer than it but not less.

**Comment by JetpackDuba** [comment]
Ah then that's probably same issue as #211.

>  think as soon as one of the special characters I added is part of the encryption string, then the length check is not matching it correctly.
Sorry I don't understand what do you mean.

**Comment by JetpackDuba** [comment]
Ah! Nevermind, I was looking into the current implementation not the one it was done initially. It was changed to initialize a random array of bytes from the beginning instead of converting a string. This is the current version:

```
private fun getRandomKey(): ByteArray {
    val byteArray = ByteArray(KEY_LENGTH)
    Random.Default.nextBytes(byteArray)

    return byteArray
}
```
