### ISSUE TITLE
erro pull/push

### ISSUE THREAD

**Issue by pedrosnow** [JetpackDuba/Gitnuro#76]
**Describe the bug**
when clicking push an error message appears about authentication not supported

**Expected behavior**
a success notice

**Screenshots**
![image](https://user-images.githubusercontent.com/37852004/215235000-7edf9332-9539-4c88-a694-a9aef5919a4e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version1.1.1

**Comment by pedrosnow** [comment]
I followed the step you can to put this snippet of code in the config

[credential]
   helper = C:/Program Files/Git/mingw64/bin/git-credential-manager-core.exe

**Comment by JetpackDuba** [comment]
I'd need the logs to have some idea of what's going on. Can you please start gitnuro from the command line and dump the logs?

> I followed the step you can to put this snippet of code in the config
> 
> [credential]
> helper = C:/Program Files/Git/mingw64/bin/git-credential-manager-core.exe

Does that path match your git credentials manager path? It may be different in your OS.

**Comment by pedrosnow** [comment]
@JetpackDuba can you give me the command to start gitnuro in the terminal

About git-credential-manager-core.exe path I will be checking tomorrow

**Comment by JetpackDuba** [comment]
Are you using the portable or installed version?

**Comment by pedrosnow** [comment]
@JetpackDuba installed version

**Comment by JetpackDuba** [comment]
Run this in Git Bash:
`C\:/Program\ Files\ \(x86\)/Gitnuro/Gitnuro.exe`

**Comment by pedrosnow** [comment]
Oops @JetpackDuba I followed your guidance of checking the correct path of the git-credential-manager-core.exe file after I found it worked

**Comment by JetpackDuba** [comment]
Nice, I'm glad you solved it :)
