### ISSUE TITLE
Start window as floating

### ISSUE THREAD

**Issue by ProjectInfinity** [JetpackDuba/Gitnuro#8]
Currently Gitnuro starts as maximized, this is really jarring if your screen is big. For instance I have 3440x1440 ultrawide screens and by default it starts stretched across the entire screen.

Changing ```placement = WindowPlacement.Maximized,```
to 
```placement = WindowPlacement.Floating,```

on line 72 in App.kt makes for a much nicer experience on large screens.

**Comment by JetpackDuba** [comment]
For small screens is not that convinient.

Preserving the window state is plan of the UX overhaul I plan to do before the release of the version 1.0.0. By default it will open as maximized but if you change it to floating, it should save the state for the next start.

Adding it to the 1.0.0 milestone.

Thanks for the feedback!
