### ISSUE TITLE
Commit messages with leading newlines don't display.

### ISSUE THREAD

**Issue by JvHummel** [JetpackDuba/Gitnuro#89]
**Describe the bug**
For some reason I have repositories where commit messages contain a leading newline. I suspect this has to do with using GitKraken as a daily driver. Gitnuro does not display commit messages for these commits in the graph.

**To Reproduce**
1. Create a commit where the commit message has a leading newline
2. See that the commit shows no text in the commit graph.

**Expected behavior**
It might be preferred to skip leading empty characters and newlines when displaying commit messages in the graph.

**Screenshots**
![220637874-5b7d0359-8bf8-414e-9e43-562169ff1980](https://user-images.githubusercontent.com/97084067/220684011-a8813b86-f23d-467c-ac03-59473ac53f45.png)

**Desktop (please complete the following information):**
 - OS: Windows 11.
 - Version: 1.1.1.

**Comment by JetpackDuba** [comment]
Hey, Thanks for the report! 
New line at the beginning of the message? What an thing odd to do :smile:  !

I've done a quick fix, it'll be available for v1.2.0

**Comment by JvHummel** [comment]
Thanks, 

I think it has to do with my tendency to only fill out the larger commit message body in GitKraken and not the small "title". To be fair I think this is mostly a strange proprietary thing GK does. 

Either way, thanks for the quick fix, it's much appreciated.

**Comment by ProjectInfinity** [comment]
> Thanks,
> 
> I think it has to do with my tendency to only fill out the larger commit message body in GitKraken and not the small "title". To be fair I think this is mostly a strange proprietary thing GK does.
> 
> Either way, thanks for the quick fix, it's much appreciated.
Do you mean going to the bottom part here?
