### ISSUE TITLE
Pressing escape should close detail view

### ISSUE THREAD

**Issue by ProjectInfinity** [JetpackDuba/Gitnuro#9]
When clicking a file either in a commit or from unstaged files you have to press the X to close the file view, allowing the Escape key to close the detail view would allow keyboard driven users to navigate the app easier.

**Comment by JetpackDuba** [comment]
I'm planning to do it for dialogs in the 1.0.0 but other components may have to wait a bit more, as there are other prioritary issues.

If the event handling is easy enough I may also implement it as I implement it for the dialogs but not sure.
