### ISSUE TITLE
Optional commit author overwrite dialog when committing

### ISSUE THREAD

**Issue by mxwell-dev** [JetpackDuba/Gitnuro#90]
**Is your feature request related to a problem? Please describe.**
We are intending to use Gitnuro for non cli-savy users on lab workstations. Because these are multi-user workstations, we often see people forgetting to update the author settings before committing something.

**Describe the solution you'd like**
The program could show a dialog which overwrites the .gitconfig settings each time a commit is done. This can be enabled in the app settings (likely the advanced settings, once Gitnuro gets to that point).

**Describe alternatives you've considered**
Having dedicated author fields above the commit button instead of a dialog, but this is easily overlooked as well and crowds the UI.

**Additional context**
We have started implementing this and will provide a PR shortly.

**Comment by mxwell-dev** [comment]
> I'm not really a fan of such specific implementation to be honest.

Well, me neither, but we had to find some solution and getting a feature like this upstream would really be the only option to make this a long term solution.

> I'd consider showing a dialog if the git credentials are not specified in the .gitconfig.

I like this idea, its quite clean.

> Not really sure about the setup, but I'd consider adding a script as a post-commit hook that clears the credentials and Gitnuro would ask them when committing.

perhaps just a checkbox that asks whether the author details should be put in the .gitconfig? if one disables this,  (and ideally the app remembers this preference), no hooks or scripts would be necessary.

> If you give me a bit more context, we could try to find a more generic way of solving the issue.

Can't really think of any more relevant context that would be of help here, but I think your proposed alternative solution would be viable. I can well imagine that this probably isn't high up on your priority list, so I'll (we'll) see what we can do to contribute code, however both kotlin and jetpack compose are completely new to me.

**Comment by JetpackDuba** [comment]
> perhaps just a checkbox that asks whether the author details should be put in the .gitconfig? if one disables this, (and ideally the app remembers this preference), no hooks or scripts would be necessary.

I like it, sounds good enough.

> 
> > If you give me a bit more context, we could try to find a more generic way of solving the issue.
> 
> Can't really think of any more relevant context that would be of help here, but I think your proposed alternative solution would be viable. I can well imagine that this probably isn't high up on your priority list, so I'll (we'll) see what we can do to contribute code, however both kotlin and jetpack compose are completely new to me.

I can do it as it's something I can do quite fast and would require evaluating the UI/UX. I can do it this weekend if you don't mind, as I'm currently implementing submodules support.

> 
> EDIT: Perhaps you'd be interest to know why we chose Gitnuro for our purpose. Well, we are a public institution, so non-free solutions are already off the table and then there just aren't that many GUIs left that are working on all three major platforms, which was important to us (just one tool to "learn"). Also Gitnuro has a simple and modern interface, and is under active development, which eliminates pretty much all remaining competitors.

Ah being a public institution gives me more motivation to do it then. 

However I must warn that the next release of gitnuro will take at least 1 more month, so you may want to generate a binary for your usecase. I can give you instructions on how to do it if you share which OS or type of executable want to use (installable/portable for windows, jar for linux or any of the macOS builds), or I can build it for you if you prefer, should be fast.

**Comment by mxwell-dev** [comment]
Thanks alot, building it should pose no problem, I've already ran it from IntelliJ, I'm sure I'll somehow handle to build a flatpak.

**Comment by JetpackDuba** [comment]
What would you think of something like this? It would show when committing and the identity is not configured.

![imagen](https://user-images.githubusercontent.com/16917468/224552218-aa21a296-0282-4d66-8c59-49d098062e72.png)

**Comment by mxwell-dev** [comment]
Looks good to me! I'm guessing you are using "Committer Identity" over "Author Details" on purpose here? Usually one just considers them to be identical and refers to both as "commit author", but git itself makes a finer distinction. What is exactly being configured? `user.name`, `author.name` or `committer.name`?. Unless Gitnuro provides an interface to all individual config fields, I think it would make sense to start with the `user.xxx` configs, which I'd put closer to "Author" than "Committer identity". But i don't really intend to nitpick about the wording here.

**Comment by JetpackDuba** [comment]
I've just used a generic name, I'll probably change it to an even more generic text such as "Author Information", as the dialog should also pop up when doing a rebase, merge or other operations. Not sure yet.

Gitnuro sets `user.name` and `user.email` in the config, so it'd be quite fitting.

**Comment by JetpackDuba** [comment]
Any feedback about it? Otherwise I'll close it as completed

**Comment by mxwell-dev** [comment]
I built it (using the fatLinux task) but only shortly tested it so far,  but it looks good to me! I think we can close this, and in case of problems open a new issue,

Thanks for the support!

**Comment by JetpackDuba** [comment]
Great! Just take in consideration that if you are using SSH, you may want to install libssh, since it's a new dependency that wasn't present in 1.1.

For debian/ubuntu: `apt install libssh-dev`
