### ISSUE TITLE
Show Username in Graph when hovering over a letter circle

### ISSUE THREAD

**Issue by Flashdown** [JetpackDuba/Gitnuro#91]
![image](https://user-images.githubusercontent.com/11328255/224951393-4fab8c02-3549-44ba-b6b1-71535a2c93cc.png)

**Comment by JetpackDuba** [comment]
I tried to do a quick implementation but apparently it wasn't as easy as I thought. I'll probably do it in 1.3 since I plan to do some changes that will help fixing this.

Thanks for your feedback!

**Comment by JetpackDuba** [comment]
Forgot to share it! 

Here goes a screenshot
![imagen](https://github.com/JetpackDuba/Gitnuro/assets/16917468/0ae29f07-157c-41b3-ae87-72e8a24f2b3a)
