### ISSUE TITLE
Add Gitnuro to Arch User Repository (AUR)

### ISSUE THREAD

**Issue by jonnypetraglia** [JetpackDuba/Gitnuro#92]
I don't see that this has been asked before but it'd be sick to have this in the AUR.

I've never actually made an AUR package but it sounds like fun so I gave it a go (for the jar). If you don't want to maintain it, I can, just figured I'd check first. Plus I don't know if you would want to track these files here or what.

https://gist.github.com/jonnypetraglia/fbcf3b4f51c8e2d5edfcbaa6f46fdba9

**Comment by JetpackDuba** [comment]
Hey! Thanks for your interest!

It wasn't asked for the AUR but for other distros. Even if I'm an archlinux user myself, I don't plan to do it. In [this issue](https://github.com/JetpackDuba/Gitnuro/issues/47) I give more details about it but quoting my main answer here:

> If the community wants to do it, they are free to, but I won't. There are tons of distros and I firmely belive that a universal solution like flatpak is the right option. I've had issues with DEB and RPM files multiple times and fixing them has been quite annoying, something that hasn't happened with Flatpak. If the performance was bad as it is with Snap, I'd consider it but I haven't noticed any difference, even in slower machines.
> 
> It would also be a hassle to test in additional environments, building and testing in 3 OS is already time consuming for a side project. That's why I decided to provide 2 versions for each OS, one with the binaries and one easy way to install it: Linux has Flatpak+JAR, MacOS brew+application and Windows Installer+Portable.
> 
> In other words, the community is free to package in whatever format they want but I won't give support to specific issues of that packaging (obviously I'll give support to issues of Gitnuro itself).

I'm using the Flatpak version on both, Arch (personal) and Ubuntu (Work), both work great without any kind of issues.

**Comment by JetpackDuba** [comment]
As I think there isn't much more to discuss for now, I'll close the issue, let me know if there is anything else.
