### ISSUE TITLE
flatpak git pull/push connection error using Git Credentials Manager

### ISSUE THREAD

**Issue by 31337-4554551n** [JetpackDuba/Gitnuro#93]
Running the app as a flatpak-and giving it flatseal permissions to access the whole drive-having configured git-config (and it working with command line git and vscodium flatpak) gitnuro gives connection issues when trying to pull/push.

It originally gave an error saying that included the URL of the git repo, but after the git-config settings in .gitconfig were modified with a second endry to point to "/run..." not just /usr the error changed to just connection error authentication dropped.

**To Reproduce**
Install gitnuro flatpak.
Configure git-config
ensure it works with git pull
Ensure it works with other flatpaks
ensure whole filesystem permissions for git nuro
Connection issues on pull/push

It to connect to the git repo and pull/push

- OS: pop is
- Version 22.04

**Comment by JetpackDuba** [comment]
Hey!

Would you mind copying and pasting this issue here? https://github.com/flathub/com.jetpackduba.Gitnuro 
It's the repository for flatpak specific issues.
