### ISSUE TITLE
Specify folder name when cloning repository

### ISSUE THREAD

**Issue by tevariedes** [JetpackDuba/Gitnuro#96]
When cloning from a remote using the URL, it would be nice to be able to specify the name of the destination folder. 

As of version 1.1.1, when cloning something like "git@gitrepo:anyrepo" to a local directory, a new folder will be created with name "git@gitrepo:anyrepo". Just a new field in the clone prompt to rename this folder would be just nice :smile:

**Comment by JetpackDuba** [comment]
Hey!

Thanks for your suggestion! I may try to do it as part of release 1.2, as I'm fixing some bugs with that dialog, but I can't promise anything.
