### ISSUE TITLE
Add action to open repo in another app (terminal, VSCode, browser, etc.)

### ISSUE THREAD

**Issue by gabeklavans** [JetpackDuba/Gitnuro#97]
**Is your feature request related to a problem? Please describe.**
When using this app as the main/primary way to interact with my git repos, it's nice to have a quick option to continue my workflow quickly into another app, like running a command in my terminal that isn't available in Gitnuro, starting dev work in VSCode, or quickly opening up the remote in my browser (e.g. going to GitHub to run an action).

**Describe the solution you'd like**
I'd like to see an action in the actions menu to open the repository externally. It doesn't have to support all the methods I've mentioned, even just opening up the default terminal and navigating to the repo's local directory would be helpful. If there were multiple options for opening externally, I'd be fine having them all listed as separate action items for quicker navigation.

**Describe alternatives you've considered**
An alternative solution could be an option to view an integrated terminal, but that would only partially solve the problem. Otherwise, I just have to open external apps manually.

**Additional context**
I've used this feature in some of my other favorite Git clients and think it could add a lot of value for not too much work here.

**Comment by JetpackDuba** [comment]
Hey! Thanks for your suggestion!

As 1.2.0, there is an option to open a terminal (#36 ) in the current repository. For now it only supports some specific hardcoded terminal emulators but in the future the users will be able to specify their own #104 .

I think that solves the issue, if there is anything else to add I can reopen the issue.

**Comment by gabeklavans** [comment]
Dang I even tried searching closed issues first, must've missed it 😅 Thanks!
